In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

data=pd.read_csv('house_price.csv', encoding='euc-kr')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


In [2]:
x=data[data[0:4]]
y=data[[5]]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)


ValueError: Boolean array expected for the condition, not object

In [3]:
x=data[data['0:4']]
y=data[['5']]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)

KeyError: '0:4'

In [4]:
x=data[data.columns['0:4']]
y=data[['5']]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [5]:
x=data[data.columns['0:4']]
y=data[['hose_price']]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [6]:
x=data[data.columns['0:4']]
y=data[['house_price']]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [7]:
x=data[data.columns[0:4]]
y=data[['house_price']]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)

KeyError: "None of [Index(['house_price'], dtype='object')] are in the [columns]"

In [8]:
x=data[data.columns[0:4]]
y=data[['house_value']]

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(x,y, train_size=0.8, random_state=42)

print(y_train.shape)
print(y_test.shape)

(14151, 1)
(3538, 1)


In [9]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(X_train)
X_sc_train=ss.transform(X_train)
X_sc_test=ss.transform(X_test)

print(X_sc_train)
print(X_sc_test)

[[-0.91849873 -0.01949449 -0.10025204 -2.0673026 ]
 [-0.38507474 -0.99179436  1.0583255  -1.33772058]
 [ 0.41506123 -0.06273694  0.36802881 -0.91969638]
 ...
 [ 1.2151972  -0.6497204   0.53982335  1.64184698]
 [-0.56288274  0.92856341 -0.70445858 -0.92591844]
 [ 0.14834924 -0.77256826 -0.38024264 -0.49381712]]
[[-0.74069073 -1.720102    0.75413535  0.99838087]
 [-0.11836275  1.43803806 -1.57052688 -0.29606748]
 [ 0.85958122  0.28562684 -0.69094018 -0.40330155]
 ...
 [-1.09630672 -1.01321903  1.42835029 -0.54859883]
 [ 0.77067722 -0.63700974  0.79857093  0.11570535]
 [-0.38507474  0.46174153 -0.31220511  1.5869434 ]]


In [10]:
from sklearn.linear_model import Ridge
model=Ridge()
model.fit(X_sc_train, y_train)
pred_train=model.predict(X_sc_train)
model.score(X_sc_train,y_train)

0.5700020252439765

In [11]:
from sklearn.linear_model import Ridge
model=Ridge()
model.fit(X_sc_train, y_train)
ridge_pred_train=model.predict(X_sc_train)
model.score(X_sc_train,y_train)

0.5700020252439765

In [12]:
ridge_pred_test=model.predict(X_sc_test)
model.socre(X_sc_test, y_test)


AttributeError: 'Ridge' object has no attribute 'socre'

In [13]:
ridge_pred_test=model.predict(X_sc_test)
model.score(X_sc_test, y_test)

0.5881679153637369

In [14]:
from sklearn.metrics import mean_square_error
ridge_mean_square_error=mean_square_error(pred_test, y_test)
print(np.sqrt(ridge_mean_square_error))

ImportError: cannot import name 'mean_square_error' from 'sklearn.metrics' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [15]:
from sklearn.metrics import mean_squared_error
ridge_mean_squared_error=mean_squared_error(pred_test, y_test)
print(np.sqrt(ridge_mean_squared_error))

NameError: name 'pred_test' is not defined

In [16]:
from sklearn.metrics import mean_squared_error
ridge_mean_squared_error=mean_squared_error(ridge_pred_test, y_test)
print(np.sqrt(ridge_mean_squared_error))

61003.1704127481


In [17]:
#ridge의 lambda가 파이썬에서는 알파로 표현된다. 이게 주요 하이퍼퍼라미러 전에는 0~1사이 값이라고 착각했었다. 0부터 다된다는소리

In [18]:
from sklearn.linear import Lasso
lasso=Lasso()
lasso.fit(X_sc_train,y_train)
lasso_train_predict=lasso.predict(X_sc_train)
print(lasso.score(X_sc_train,y_train))

ModuleNotFoundError: No module named 'sklearn.linear'

In [19]:
from sklearn.linear_model import Lasso
lasso=Lasso()
lasso.fit(X_sc_train,y_train)
lasso_train_predict=lasso.predict(X_sc_train)
print(lasso.score(X_sc_train,y_train))

0.5700020371636806


In [20]:
lass_test_preidct=lasso.predict(X_sc_test)
print("lasso test set score", lasso.score(X_sc_test, y_test))

lasso test set score 0.588168061776849


In [21]:
Lasso_mean_squared_error=mean_squared_error(lass_test_preidct, y_test)
print("RMSE LASSO test set score", np.sqrt(Lasso_mean_squared_error))

NameError: name 'lass_test_predict' is not defined

In [22]:
Lasso_mean_squared_error=mean_squared_error(lass_test_preidct, y_test)
print("RMSE LASSO test set score", np.sqrt(Lasso_mean_squared_error))

RMSE LASSO test set score 61003.15956892952


In [23]:
from sklearn.linear_model import Elasticnet
ela=Elasticnet()
ela.fit(X_sc_train, y_train)
print("Elasticnet Regressor Train", ela.score(X_sc_train, y_train))

ImportError: cannot import name 'Elasticnet' from 'sklearn.linear_model' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/__init__.py)

In [24]:
from sklearn.linear_model import ElasticNet
ela=ElasticNet()
ela.fit(X_sc_train, y_train)
print("Elasticnet Regressor Train", ela.score(X_sc_train, y_train))

Elasticnet Regressor Train 0.453382523729442


In [25]:
ela_test_predict=ela.predict(X_sc_test)
print("ElasticNet", ela.score(X_sc_test, y_test))

ElasticNet 0.46927473037944867


In [26]:
ela_mean_squared_error=mean_squared_error(ela_test_predict, y_test)
print("ElasticNet RMSE", np,sqrt(ela_mean_squared_error))


NameError: name 'sqrt' is not defined

In [27]:
ela_mean_squared_error=mean_squared_error(ela_test_predict, y_test)
print("ElasticNet RMSE", np.sqrt(ela_mean_squared_error))

ElasticNet RMSE 69251.18359992556
