In [1]:
import numpy as np

abs2=np.abs(-2)
abs2

2

In [2]:
sqrt=np.sqrt(4)
sqrt

2.0

In [3]:
square=np.square(4)
square

16

In [4]:
exp=nump.exp(4)
exp

NameError: name 'nump' is not defined

In [5]:
exp=np.exp(4)
exp

54.598150033144236

In [6]:
log=numpy.log(4)

NameError: name 'numpy' is not defined

In [7]:
log=np.log(4)

In [8]:
log=

SyntaxError: invalid syntax (<ipython-input-8-b076f26a822a>, line 1)

In [9]:
log

1.3862943611198906

In [10]:
v1=np.array([1,2,3,4])
v1

array([1, 2, 3, 4])

In [11]:
v1=np.aragne(5)
v1

AttributeError: module 'numpy' has no attribute 'aragne'

In [12]:
v1=np.arange(5)
v1

array([0, 1, 2, 3, 4])

In [13]:
v2=np.array(1,10,2)
v2

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [14]:
v2=np.arange(1,10,2)
v2

array([1, 3, 5, 7, 9])

In [15]:
v3=np.arange(3.5,10.5,2, dtype=float)
v3

array([3.5, 5.5, 7.5, 9.5])

In [16]:
v4=np.arange(1,10,2)**2
v4

array([ 1,  9, 25, 49, 81])

In [17]:
v5=np.arange(1,10,2)**3

In [18]:
v5

array([  1,  27, 125, 343, 729])

In [19]:
v6=np.array(12)

In [20]:
v6

array(12)

In [21]:
v6=np.arange(12)

In [22]:
v6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
v7=v6.rearange(2,2)

AttributeError: 'numpy.ndarray' object has no attribute 'rearange'

In [24]:
v7=v6.reshape(2,2)

ValueError: cannot reshape array of size 12 into shape (2,2)

In [25]:
v6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
v7=v6.reshape(2,2)

ValueError: cannot reshape array of size 12 into shape (2,2)

In [27]:
v7=v6.reshape(2,6)

In [28]:
v7

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
#reshape 할때 (차원, 한행에 들어가는 갯수, 한 열에 들어가는 갯수)라고 생각해야 이해가 편하다. 

In [30]:
v8=v6.reshape(2,6, order='F')
v8

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [31]:
v9=arange(1:5).reshape(2,2)
v9

SyntaxError: invalid syntax (<ipython-input-31-b4b78bb95445>, line 1)

In [32]:
v9=arange(1,5).reshape(2,2)
v9

NameError: name 'arange' is not defined

In [33]:
v9=np.arange(1,5).reshape(2,2)
v9

array([[1, 2],
       [3, 4]])

In [34]:
v10=np.add(v9,v9)
v10=np.add(v9,v9)
v10=np.add(v9,v9)
v10

array([[2, 4],
       [6, 8]])

In [35]:
v11=np.subtract(v9,v9)
v11

array([[0, 0],
       [0, 0]])

In [36]:
v12=np.mulipliy(v9,v9)
v12

AttributeError: module 'numpy' has no attribute 'mulipliy'

In [37]:
v12=np.multiply(v9,v9)
v12

array([[ 1,  4],
       [ 9, 16]])

In [38]:
v13=np.dot(v9,v9)
v13

array([[ 7, 10],
       [15, 22]])

In [39]:
v14=np.reshape(2,2,3)
v14

TypeError: order must be str, not int

In [40]:
v14=v9.reshape(2,2,3)
v14

ValueError: cannot reshape array of size 4 into shape (2,2,3)

In [41]:
v1=np.arange(12)
v14=v1.reshape(2,3,2)
v14

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [42]:
v3=np.arange(3.5,10.5,2)
v4=np.arange(1,5).reshape(2,2)
print(v3)
print(v4)


[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]


In [43]:
v1=np.arange(12)
v14=v1.reshape(2,3)
v14

ValueError: cannot reshape array of size 12 into shape (2,3)

In [44]:
v1=np.arange(12)
v14=v1.reshape(2,3,2)
v14

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [45]:
print(np.amax(v3))
print(np.amin(v4))


9.5
1


In [46]:
print(v4.shape)
print(v14.shape)

(2, 2)
(2, 3, 2)


In [47]:
v4

array([[1, 2],
       [3, 4]])

In [48]:
import pandas as pd
from pandas import Series, DataFrame 
a=Series([1,3,5,7])
print(a)
print(a.values)
print(a.index)
a2=pd.series([1,3,5,7], index=['a','b','c','d'])
print(a2)


0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)


AttributeError: module 'pandas' has no attribute 'series'

In [49]:
import pandas as pd
from pandas import Series, DataFrame 
a=Series([1,3,5,7])
print(a)
print(a.values)
print(a.index)
a2=pd.Series([1,3,5,7], index=['a','b','c','d'])
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64


In [50]:
df=pd.read_csv('Ex_GrapeData.csv')
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [51]:
df[1:4]


continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69

In [52]:
df[1:5]

continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [53]:
df[:2]


continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215

In [54]:
df[:3]


continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105

In [55]:
df[60:]


continent  brand  size  period price
60          2      2   5.0    12.0      
61          2      3  13.0    20.0      
62          2      3  31.0    19.0

In [56]:
data[['price']]


NameError: name 'data' is not defined

In [57]:
df[['price']]

price
0    144
1    215
2    105
3     69
4    134
..   ...
58  21.5
59      
60      
61      
62      

[63 rows x 1 columns]

In [58]:
df[df.columns[[0,2,4]]

SyntaxError: unexpected EOF while parsing (<ipython-input-58-e11b558c1d59>, line 1)

In [59]:
df[df.columns[[0,2,4]]]

continent  size price
0           2  10.7   144
1           2  14.0   215
2           2   9.0   105
3           1   8.0    69
4           2  10.0   134
..        ...   ...   ...
58          1   5.0  21.5
59          2  21.0      
60          2   5.0      
61          2  13.0      
62          2  31.0      

[63 rows x 3 columns]

In [60]:
df.loc[:,'size':'price']

size  period price
0   10.7   47.65   144
1   14.0   63.13   215
2    9.0   58.76   105
3    8.0   34.88    69
4   10.0   55.53   134
..   ...     ...   ...
58   5.0   16.66  21.5
59  21.0   43.00      
60   5.0   12.00      
61  13.0   20.00      
62  31.0   19.00      

[63 rows x 3 columns]

In [61]:
dt.iloc[1:7, 0:2]


NameError: name 'dt' is not defined

In [62]:
df.iloc[1:7, 0:2]

continent  brand
1          2      3
2          2      2
3          1      1
4          2      2
5          2      2
6          2      2

In [63]:
df['price'].at(5)

TypeError: '_AtIndexer' object is not callable

In [64]:
df.at[5, 'price']

'129'

In [65]:
case=data.copy()
case

NameError: name 'data' is not defined

In [66]:
case=df.copy()
case

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [67]:
data.columns

NameError: name 'data' is not defined

In [68]:
df.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [69]:
df.rename({'period':'time'})
df.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [70]:
df.rename(columns={'period':'time'}, inplace=True)
df.columns

Index(['continent', 'brand', 'size', 'time', 'price'], dtype='object')

In [71]:
df.rename(columns={'time':'period'}, inplace=True)
df.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [72]:
df.rename(columns={'period':'time'}, inplace=True)
df.columns

Index(['continent', 'brand', 'size', 'time', 'price'], dtype='object')

In [73]:
df['Growth']=df.size/df.time


In [74]:
df.head()

continent  brand  size   time price    Growth
0          2      2  10.7  47.65   144  6.610703
1          2      3  14.0  63.13   215  4.989704
2          2      2   9.0  58.76   105  5.360790
3          1      1   8.0  34.88    69  9.030963
4          2      2  10.0  55.53   134  5.672609

In [75]:
df['Growth']=df['size']/df['time']
df.head()

continent  brand  size   time price    Growth
0          2      2  10.7  47.65   144  0.224554
1          2      3  14.0  63.13   215  0.221765
2          2      2   9.0  58.76   105  0.153165
3          1      1   8.0  34.88    69  0.229358
4          2      2  10.0  55.53   134  0.180083

In [76]:
time1=df.time
time1

0     47.65
1     63.13
2     58.76
3     34.88
4     55.53
      ...  
58    16.66
59    43.00
60    12.00
61    20.00
62    19.00
Name: time, Length: 63, dtype: float64

In [77]:
size2=df.size
size2

378

In [78]:
size=df.size
size

378

In [79]:
#아무래도 size라는 매쏘드가 있어서 이런현상이 나온듯하다. 

In [80]:
del df['Growth']
df.head()

continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215
2          2      2   9.0  58.76   105
3          1      1   8.0  34.88    69
4          2      2  10.0  55.53   134

In [81]:
case1=df[(df['continent']==1)&(df['brand']==1)]
case1

continent  brand  size   time price
3           1      1   8.0  34.88    69
11          1      1  10.4  17.67    54
12          1      1   7.4  16.41    39
13          1      1   5.4  12.02  29.5
16          1      1   6.0  23.21    42
17          1      1   9.0  28.64    65
19          1      1  12.4  23.77  49.5
20          1      1   7.5  20.21  36.5
22          1      1   7.0  17.84    45
25          1      1   5.5  15.61    30
42          1      1  10.0  31.86  43.5
47          1      1   8.0  21.34    42
53          1      1   8.5  30.20  54.5
54          1      1   6.0  20.85  24.5
58          1      1   5.0  16.66  21.5

In [82]:
case2=df[(df['size']>=10)&(df['period']>30)]
case2

KeyError: 'period'

In [83]:
case2=df[(df['size']>=10)&(df['time']>30)]
case2

continent  brand  size    time price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
4           2      2  10.0   55.53   134
5           2      2  10.5   43.14   129
6           2      2  16.0   54.86   155
7           2      1  15.0   44.14    99
10          2      2  25.0  109.38   260
14          2      2  15.4   49.48   109
15          2      1  12.4   48.74  89.5
21          1      3  14.0   32.62   109
27          1      3  12.0   45.78   119
29          1      3  14.2   37.11   109
30          2      2  11.0   45.12    99
32          2      3  13.5   68.63   179
33          2      2  11.1   33.71    99
36          2      3  13.0   86.42   199
37          1      3  13.0   39.71    93
39          2      2  12.3   33.89    74
40          2      3  19.5   64.30   165
42          1      1  10.0   31.86  43.5
43          1      3  11.0   53.18    94
44          2      3  17.8   74.48   189
45          2      2  11.5   34.16    75
46          2      1  12.7   31.46  59.5
50          2      2  14.0   33.70    99
51          2      2  12.4   32.90    89
59          2      1  21.0   43.00

In [84]:
replace_brand={'brand':{1:1,2:1,3:2}}


In [85]:
df_recode=df.replace(replace_brand)
df.recode.head()

AttributeError: 'DataFrame' object has no attribute 'recode'

In [86]:
df_recode=df.replace(replace_brand)
df_recode.head()

continent  brand  size   time price
0          2      1  10.7  47.65   144
1          2      2  14.0  63.13   215
2          2      1   9.0  58.76   105
3          1      1   8.0  34.88    69
4          2      1  10.0  55.53   134

In [87]:
replace_brand={'brand':{1:1,2:1,3:2}}
#키값을 주고 또주고가 되네;; 어렵다 

In [88]:
replace_brand={'brand':{1:1,2:1,3:2}}
df_recode=df.replace(replace_brand)
df_recode.head()


continent  brand  size   time price
0          2      1  10.7  47.65   144
1          2      2  14.0  63.13   215
2          2      1   9.0  58.76   105
3          1      1   8.0  34.88    69
4          2      1  10.0  55.53   134

In [89]:
def brand_groups(series):
    if series==1:
        return 1
    elif series==2:
        return 1
    elif series==3:
        return 2
    
df['re_brand']=df['brand'].apply(brand_group)
df.head()

NameError: name 'brand_group' is not defined

In [90]:
def brand_groups(series):
    if series==1:
        return 1
    elif series==2:
        return 1
    elif series==3:
        return 2
    
df['re_brand']=df['brand'].apply(brand_groups)
df.head()

continent  brand  size   time price  re_brand
0          2      2  10.7  47.65   144         1
1          2      3  14.0  63.13   215         2
2          2      2   9.0  58.76   105         1
3          1      1   8.0  34.88    69         1
4          2      2  10.0  55.53   134         1

In [91]:
df_num=df.to_numpy()
df_num

array([[2, 2, 10.7, 47.65, '144', 1],
       [2, 3, 14.0, 63.13, '215', 2],
       [2, 2, 9.0, 58.76, '105', 1],
       [1, 1, 8.0, 34.88, '69', 1],
       [2, 2, 10.0, 55.53, '134', 1],
       [2, 2, 10.5, 43.14, '129', 1],
       [2, 2, 16.0, 54.86, '155', 1],
       [2, 1, 15.0, 44.14, '99', 1],
       [2, 1, 6.5, 17.46, '38.5', 1],
       [2, 1, 5.0, 21.04, '36.5', 1],
       [2, 2, 25.0, 109.38, '260', 1],
       [1, 1, 10.4, 17.67, '54', 1],
       [1, 1, 7.4, 16.41, '39', 1],
       [1, 1, 5.4, 12.02, '29.5', 1],
       [2, 2, 15.4, 49.48, '109', 1],
       [2, 1, 12.4, 48.74, '89.5', 1],
       [1, 1, 6.0, 23.21, '42', 1],
       [1, 1, 9.0, 28.64, '65', 1],
       [1, 3, 9.0, 44.95, '115', 2],
       [1, 1, 12.4, 23.77, '49.5', 1],
       [1, 1, 7.5, 20.21, '36.5', 1],
       [1, 3, 14.0, 32.62, '109', 2],
       [1, 1, 7.0, 17.84, '45', 1],
       [1, 2, 9.0, 22.82, '58', 1],
       [1, 2, 12.0, 29.48, '89', 1],
       [1, 1, 5.5, 15.61, '30', 1],
       [1, 2, 6.0, 13.25, '3

In [92]:
df_num=df.to_numpy()
df_num

df_num=df.to_numpy()
df_num

array([[2, 2, 10.7, 47.65, '144', 1],
       [2, 3, 14.0, 63.13, '215', 2],
       [2, 2, 9.0, 58.76, '105', 1],
       [1, 1, 8.0, 34.88, '69', 1],
       [2, 2, 10.0, 55.53, '134', 1],
       [2, 2, 10.5, 43.14, '129', 1],
       [2, 2, 16.0, 54.86, '155', 1],
       [2, 1, 15.0, 44.14, '99', 1],
       [2, 1, 6.5, 17.46, '38.5', 1],
       [2, 1, 5.0, 21.04, '36.5', 1],
       [2, 2, 25.0, 109.38, '260', 1],
       [1, 1, 10.4, 17.67, '54', 1],
       [1, 1, 7.4, 16.41, '39', 1],
       [1, 1, 5.4, 12.02, '29.5', 1],
       [2, 2, 15.4, 49.48, '109', 1],
       [2, 1, 12.4, 48.74, '89.5', 1],
       [1, 1, 6.0, 23.21, '42', 1],
       [1, 1, 9.0, 28.64, '65', 1],
       [1, 3, 9.0, 44.95, '115', 2],
       [1, 1, 12.4, 23.77, '49.5', 1],
       [1, 1, 7.5, 20.21, '36.5', 1],
       [1, 3, 14.0, 32.62, '109', 2],
       [1, 1, 7.0, 17.84, '45', 1],
       [1, 2, 9.0, 22.82, '58', 1],
       [1, 2, 12.0, 29.48, '89', 1],
       [1, 1, 5.5, 15.61, '30', 1],
       [1, 2, 6.0, 13.25, '3

In [93]:
df=pd.DataFrame(df_num)
df

0  1     2      3     4  5
0   2  2  10.7  47.65   144  1
1   2  3  14.0  63.13   215  2
2   2  2   9.0  58.76   105  1
3   1  1   8.0  34.88    69  1
4   2  2  10.0  55.53   134  1
.. .. ..   ...    ...   ... ..
58  1  1   5.0  16.66  21.5  1
59  2  1  21.0   43.0        1
60  2  2   5.0   12.0        1
61  2  3  13.0   20.0        2
62  2  3  31.0   19.0        2

[63 rows x 6 columns]

In [94]:
df2=pd.DataFrame(data=data.num, columns=["continent", 'brand', 'size', 'period', 'price'])
df2

NameError: name 'data' is not defined

In [95]:
df2=pd.DataFrame(data=df.num, columns=["continent", 'brand', 'size', 'period', 'price'])
df2

AttributeError: 'DataFrame' object has no attribute 'num'

In [96]:
df2=pd.DataFrame(data=df_num, columns=["continent", 'brand', 'size', 'period', 'price'])
df2

AssertionError: Number of manager items must equal union of block items
# manager items: 5, # tot_items: 6

In [97]:
df2=pd.DataFrame(data=df_num, columns=['continent', 'brand', 'size', 'period', 'price'])
df2.head()

AssertionError: Number of manager items must equal union of block items
# manager items: 5, # tot_items: 6

In [98]:
df_num

array([[2, 2, 10.7, 47.65, '144', 1],
       [2, 3, 14.0, 63.13, '215', 2],
       [2, 2, 9.0, 58.76, '105', 1],
       [1, 1, 8.0, 34.88, '69', 1],
       [2, 2, 10.0, 55.53, '134', 1],
       [2, 2, 10.5, 43.14, '129', 1],
       [2, 2, 16.0, 54.86, '155', 1],
       [2, 1, 15.0, 44.14, '99', 1],
       [2, 1, 6.5, 17.46, '38.5', 1],
       [2, 1, 5.0, 21.04, '36.5', 1],
       [2, 2, 25.0, 109.38, '260', 1],
       [1, 1, 10.4, 17.67, '54', 1],
       [1, 1, 7.4, 16.41, '39', 1],
       [1, 1, 5.4, 12.02, '29.5', 1],
       [2, 2, 15.4, 49.48, '109', 1],
       [2, 1, 12.4, 48.74, '89.5', 1],
       [1, 1, 6.0, 23.21, '42', 1],
       [1, 1, 9.0, 28.64, '65', 1],
       [1, 3, 9.0, 44.95, '115', 2],
       [1, 1, 12.4, 23.77, '49.5', 1],
       [1, 1, 7.5, 20.21, '36.5', 1],
       [1, 3, 14.0, 32.62, '109', 2],
       [1, 1, 7.0, 17.84, '45', 1],
       [1, 2, 9.0, 22.82, '58', 1],
       [1, 2, 12.0, 29.48, '89', 1],
       [1, 1, 5.5, 15.61, '30', 1],
       [1, 2, 6.0, 13.25, '3

In [99]:
df2=pd.DataFrame(data=df_num, columns=['continent', 'brand', 'size', 'period', 'price', 're_brand'])
df2.head()

continent brand  size period price re_brand
0         2     2  10.7  47.65   144        1
1         2     3  14.0  63.13   215        2
2         2     2   9.0  58.76   105        1
3         1     1   8.0  34.88    69        1
4         2     2  10.0  55.53   134        1