In [1]:
S="Influlencer"
b="hang"
c="shu"


In [2]:
print(S+b+c)

Influlencerhangshu


In [3]:
a=

SyntaxError: invalid syntax (<ipython-input-3-2d920c342ece>, line 1)

In [4]:
a="Wise in Company"
print(a[0:15])

Wise in Company


In [5]:
b="Berry will meet me"

In [6]:
=print(a[0:5])

SyntaxError: invalid syntax (<ipython-input-6-53f9a86490fb>, line 1)

In [7]:
=print(b[0:5])

SyntaxError: invalid syntax (<ipython-input-7-c89e1690d0dd>, line 1)

In [8]:
b


'Berry will meet me'

In [9]:
print(b[1])

e


In [10]:
=print(b[0:4])

SyntaxError: invalid syntax (<ipython-input-10-3168b430ce10>, line 1)

In [11]:
print(a[0:4])

Wise


In [12]:
print(b[0:4])

Berr


In [13]:
print(b[0:5])

Berry


In [14]:
print(b[5:])

 will meet me


In [15]:
a=[a,2,c,4,e]
print(a)

NameError: name 'e' is not defined

In [16]:
a=[1,b]

In [17]:
print(a)

[1, 'Berry will meet me']


In [18]:
a=[1,2,3,4,5]

In [19]:
a.append(7)

In [20]:
a(1)=13

SyntaxError: cannot assign to function call (<ipython-input-20-7e8c6bc233ac>, line 1)

In [21]:
a[1]=13

In [22]:
print(a)

[1, 13, 3, 4, 5, 7]


In [23]:
print(a[0:2])

[1, 13]


In [24]:
p=a*3

In [25]:
p

[1, 13, 3, 4, 5, 7, 1, 13, 3, 4, 5, 7, 1, 13, 3, 4, 5, 7]

In [26]:
del.p(13)

SyntaxError: invalid syntax (<ipython-input-26-20c3ec236151>, line 1)

In [27]:
del b[2]

TypeError: 'str' object doesn't support item deletion

In [28]:
del p[13]

In [29]:
p

[1, 13, 3, 4, 5, 7, 1, 13, 3, 4, 5, 7, 1, 3, 4, 5, 7]

In [30]:
t=('마리''고리''보리''사리''다리')

In [31]:
print(t(0))

TypeError: 'str' object is not callable

In [32]:
print(t[0])

마


In [33]:
print(t[0:2])

마리


In [34]:
여자1, 여자2, 여자3, 여자 4, 여자 5=('마리','고리','보리','사리','다리')

SyntaxError: invalid syntax (<ipython-input-34-16c617572266>, line 1)

In [35]:
여자1, 여자2, 여자3, 여자4, 여자5=('마리','고리','보리','사리','다리')

In [36]:
여자1

'마리'

In [37]:
여자2

'고리'

In [38]:
여자1+여자2

'마리고리'

In [39]:
set={"berry", "will", "meet", "me", "berry"}

In [40]:
set

{'berry', 'me', 'meet', 'will'}

In [41]:
t.remove("마리")

AttributeError: 'str' object has no attribute 'remove'

In [42]:
import numpy as np
v1=np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [43]:
v1=np.arange(5)
print(v1)

[0 1 2 3 4]


In [44]:
v1=np.arragne(8)
print(v1)

AttributeError: module 'numpy' has no attribute 'arragne'

In [45]:
v1=np.arange(8)
print(v1)

[0 1 2 3 4 5 6 7]


In [46]:
v2=np.aragne(1,10,2)
v3=np.aragne(3.5,10.5,2)
print(v2)
print(v3)


AttributeError: module 'numpy' has no attribute 'aragne'

In [47]:
v2=np.aragne(1,10,2,)
v3=np.aragne(3.5,10.5,2,)
print(v2)
print(v3)

AttributeError: module 'numpy' has no attribute 'aragne'

In [48]:
v2=np.aragne(1,10,2,dtpye=int)
v3=np.aragne(3.5,10.5,2, dtpye=float)
print(v2)
print(v3)

AttributeError: module 'numpy' has no attribute 'aragne'

In [49]:
v2=np.arange(1,10,2,)
v3=np.arange(3.5,10.5,2,)
print(v2)
print(v3)

[1 3 5 7 9]
[3.5 5.5 7.5 9.5]


In [50]:
v2=np.arange(1,10,2)
v3=np.arange(3.5,10.5,2)
print(v2)
print(v3)

[1 3 5 7 9]
[3.5 5.5 7.5 9.5]


In [51]:
v4=np.arange(1,10,2)**2
print(v4)

[ 1  9 25 49 81]


In [52]:
v5=np.arange(1,10,2)**3
print(v5)


[  1  27 125 343 729]


In [53]:
v1=np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
v2=v1.reshape(2,6)
print=(v2)

In [55]:
print=(v2)

In [56]:
v2=v1.reshape(2,6)
print=(v2)

In [57]:
v1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
v2=v1.reshape(2,6)
print(v2)

TypeError: 'numpy.ndarray' object is not callable

In [59]:
v1=np.arange(12)
print(v1)

TypeError: 'numpy.ndarray' object is not callable

In [60]:
v1=np.arange(12)
print(v1)

TypeError: 'numpy.ndarray' object is not callable

In [61]:
v1=np.arange(12)

In [62]:
print(v1)

TypeError: 'numpy.ndarray' object is not callable

In [63]:
import numpy as np
v1=np.arange(12)
print(v1)

TypeError: 'numpy.ndarray' object is not callable

In [64]:
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
v2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
v3=v1.reshape(2,6, order='F')

In [67]:
v3

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [68]:
v3=v1.reshape(2,6,2, order='F')

SyntaxError: invalid syntax (<ipython-input-68-6bf9d7c0cd00>, line 1)

In [69]:
v3=v1.reshape(2,6,2, order='F')

ValueError: cannot reshape array of size 12 into shape (2,6,2)

In [70]:
import pandas as pd
df=pd.read_csv('EX_GrapeData.csv')
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [71]:
df.head()

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [72]:
df.tail()

continent  brand  size  period price
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00

In [73]:
df(1:5)

SyntaxError: invalid syntax (<ipython-input-73-92d635077bb1>, line 1)

In [74]:
df[1:5]

continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [75]:
df[0:4]

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69

In [76]:
df[:42]

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
5           2      2  10.5   43.14   129
6           2      2  16.0   54.86   155
7           2      1  15.0   44.14    99
8           2      1   6.5   17.46  38.5
9           2      1   5.0   21.04  36.5
10          2      2  25.0  109.38   260
11          1      1  10.4   17.67    54
12          1      1   7.4   16.41    39
13          1      1   5.4   12.02  29.5
14          2      2  15.4   49.48   109
15          2      1  12.4   48.74  89.5
16          1      1   6.0   23.21    42
17          1      1   9.0   28.64    65
18          1      3   9.0   44.95   115
19          1      1  12.4   23.77  49.5
20          1      1   7.5   20.21  36.5
21          1      3  14.0   32.62   109
22          1      1   7.0   17.84    45
23          1      2   9.0   22.82    58
24          1      2  12.0   29.48    89
25          1      1   5.5   15.61    30
26          1      2   6.0   13.25    31
27          1      3  12.0   45.78   119
28          2      1   5.5   26.53    22
29          1      3  14.2   37.11   109
30          2      2  11.0   45.12    99
31          1      2  16.0   26.09    99
32          2      3  13.5   68.63   179
33          2      2  11.1   33.71    99
34          2      3   9.8   44.45    89
35          1      2  10.0   23.74    75
36          2      3  13.0   86.42   199
37          1      3  13.0   39.71    93
38          1      2  11.7   26.52    65
39          2      2  12.3   33.89    74
40          2      3  19.5   64.30   165
41          1      3  15.2   22.55    99

In [77]:
df['price']

0      144
1      215
2      105
3       69
4      134
      ... 
58    21.5
59        
60        
61        
62        
Name: price, Length: 63, dtype: object

In [78]:
df[['price']]

price
0    144
1    215
2    105
3     69
4    134
..   ...
58  21.5
59      
60      
61      
62      

[63 rows x 1 columns]

In [79]:
df[df.columns[[0,2,4]]]

continent  size price
0           2  10.7   144
1           2  14.0   215
2           2   9.0   105
3           1   8.0    69
4           2  10.0   134
..        ...   ...   ...
58          1   5.0  21.5
59          2  21.0      
60          2   5.0      
61          2  13.0      
62          2  31.0      

[63 rows x 3 columns]

In [80]:
df.loc[:,'size','price']

IndexingError: Too many indexers

In [81]:
df.loc[:,'size':'price']

size  period price
0   10.7   47.65   144
1   14.0   63.13   215
2    9.0   58.76   105
3    8.0   34.88    69
4   10.0   55.53   134
..   ...     ...   ...
58   5.0   16.66  21.5
59  21.0   43.00      
60   5.0   12.00      
61  13.0   20.00      
62  31.0   19.00      

[63 rows x 3 columns]

In [82]:
df.iloc[1:7, 0:2]

continent  brand
1          2      3
2          2      2
3          1      1
4          2      2
5          2      2
6          2      2

In [83]:
df_columns.columns

NameError: name 'df_columns' is not defined

In [84]:
df_columns.columns


NameError: name 'df_columns' is not defined

In [85]:
df_columns.columns

NameError: name 'df_columns' is not defined

In [86]:
df.head()

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [87]:
df_columns=df.copy()

In [88]:
df_columns.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [89]:
df.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [90]:
df.columns.rename(columns={"perid","time"}, inplace=true)
df_columns.columns

NameError: name 'true' is not defined

In [91]:
df.columns.rename(columns={"perid","time"}, inplace=True)
df_columns.columns

TypeError: rename() got an unexpected keyword argument 'columns'

In [92]:
df_columns.rename(columns={'period':'time'}, inplace=True)
df_columns.columns


Index(['continent', 'brand', 'size', 'time', 'price'], dtype='object')

In [93]:
df_columns.rename(columns={"period":"time"}, inplace=True)
df_columns.columns



Index(['continent', 'brand', 'size', 'time', 'price'], dtype='object')

In [94]:
df_continent_brand=df[(df['continent']==1)&(df['brand']==1)]
df_continent_brand.head()


continent  brand  size  period price
3           1      1   8.0   34.88    69
11          1      1  10.4   17.67    54
12          1      1   7.4   16.41    39
13          1      1   5.4   12.02  29.5
16          1      1   6.0   23.21    42