In [1]:
v1=np.arange(1,5).reshape(2,2)
print(np.dot(v1,v1))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
v1=np.arange(1,5).reshape(2,2)
print(np.dot(v1,v1))

[[ 7 10]
 [15 22]]


In [5]:
v1

array([[1, 2],
       [3, 4]])

In [6]:
v1=np.arange(5)
v1

array([0, 1, 2, 3, 4])

In [7]:
v1=np.arange([1,2,3,4])
v1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [8]:
v1=np.array([1,2,3,4])
v1

array([1, 2, 3, 4])

In [9]:
v1=np.array([1,2,3,4])
v1

array([1, 2, 3, 4])

In [10]:
v2=np.arange(6)
print(v2)

[0 1 2 3 4 5]


In [12]:
v3=np.aragne(1,10,2)
print(v3)

AttributeError: module 'numpy' has no attribute 'aragne'

In [13]:
v3=np.arange(1,10,2)
print(v3)

[1 3 5 7 9]


In [14]:
v4=np.arange(3.5,10.5,2, dtype=float)
prinit(v4)

NameError: name 'prinit' is not defined

In [15]:
v4=np.arange(3.5,10.5,2, dtype=float)
print(v4)

[3.5 5.5 7.5 9.5]


In [16]:
v5=v3**2
print(v5)

[ 1  9 25 49 81]


In [17]:
v6=v3**3

In [18]:
print(v6)

[  1  27 125 343 729]


In [19]:
v7=np.arange(12)
print(v7)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
v8=v7.reshape(2,6)
print(v8)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [21]:
v9=v7.reshape(2,6, order='F')
print(v9)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [22]:
v10=np.arange(1:4)
v10.rearange(2,2)
print(v10)

SyntaxError: invalid syntax (<ipython-input-22-f924eaa9959b>, line 1)

In [23]:
v10=np.arange(1,4)
v10.rearange(2,2)
print(v10)

AttributeError: 'numpy.ndarray' object has no attribute 'rearange'

In [24]:
v10=np.arange(1,4)
v10.reshape(2,2)
print(v10)

ValueError: cannot reshape array of size 3 into shape (2,2)

In [25]:
v10=np.arange(1,5)
v10.reshape(2,2)
print(v10)

[1 2 3 4]


In [26]:
print(np.add(v1,v1))


[2 4 6 8]


In [27]:
print(np.substract(v1,v1))


AttributeError: module 'numpy' has no attribute 'substract'

In [28]:
rint(np.subtract(v1,v1))

NameError: name 'rint' is not defined

In [29]:
print(np.subtract(v1,v1))

[0 0 0 0]


In [30]:
print(np.multiply(v1,v1))

[ 1  4  9 16]


In [31]:
print(np.dot(v1,v1))

30


In [32]:
print(np.add(v10,v10))

[2 4 6 8]


In [33]:
v10=np.arange(1,5).reshape(2,2)
print(v10)

[[1 2]
 [3 4]]


In [34]:
print(np.add(v10,v10))
print(np.subtract(v10,v10))
print(np.multiply(v10,v10))


[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]


In [35]:
print(np.dot(v10,v10))


[[ 7 10]
 [15 22]]


In [36]:
v1=np.arange(12)


In [37]:
v2=v1.reshape(2,3,2)
print(v2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [38]:
v3=v1.reshape(2,3,2, order='F')

In [39]:
print(v3)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [40]:
import pandas as pd
from pandas import Series, DataFrame

In [41]:
a=Series([1,3,5,7])
print(a)

0    1
1    3
2    5
3    7
dtype: int64


In [42]:
print(a.values)

[1 3 5 7]


In [43]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)


In [44]:
a2=pd.Series([1,3,5,7], index=['a','b','c','d'])
print(a2)


a    1
b    3
c    5
d    7
dtype: int64


In [45]:
df=pd.read_csv('EX_GrapeData.csv')
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [46]:
df=pd.read_csv('EX_grapeData.csv', encoding='euc-kr')


In [47]:
df[1:4]

continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69

In [48]:
df[1:5]

continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [49]:
df[:2]

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215

In [50]:
df[:3]

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105

In [51]:
df[60:]

continent  brand  size  period price
60          2      2   5.0    12.0      
61          2      3  13.0    20.0      
62          2      3  31.0    19.0

In [52]:
data['price']

NameError: name 'data' is not defined

In [53]:
df['price']

0      144
1      215
2      105
3       69
4      134
      ... 
58    21.5
59        
60        
61        
62        
Name: price, Length: 63, dtype: object

In [54]:
df[['price']]

price
0    144
1    215
2    105
3     69
4    134
..   ...
58  21.5
59      
60      
61      
62      

[63 rows x 1 columns]

In [55]:
df[[0,2,4]]

KeyError: "None of [Int64Index([0, 2, 4], dtype='int64')] are in the [columns]"

In [56]:
df[df.columns[[0,2,4]]

SyntaxError: unexpected EOF while parsing (<ipython-input-56-e11b558c1d59>, line 1)

In [57]:
df[df.columns[[0,2,4]]]

continent  size price
0           2  10.7   144
1           2  14.0   215
2           2   9.0   105
3           1   8.0    69
4           2  10.0   134
..        ...   ...   ...
58          1   5.0  21.5
59          2  21.0      
60          2   5.0      
61          2  13.0      
62          2  31.0      

[63 rows x 3 columns]

In [58]:
#왜 여기는 데이터셋을 두번 불러와야할까? 

In [59]:
df.loc[:. 'size':'price']

SyntaxError: invalid syntax (<ipython-input-59-e1e4ed13c7c6>, line 1)

In [60]:
df.loc[:, 'size':'price']

size  period price
0   10.7   47.65   144
1   14.0   63.13   215
2    9.0   58.76   105
3    8.0   34.88    69
4   10.0   55.53   134
..   ...     ...   ...
58   5.0   16.66  21.5
59  21.0   43.00      
60   5.0   12.00      
61  13.0   20.00      
62  31.0   19.00      

[63 rows x 3 columns]

In [61]:
df.iloc[1:7, 0:2\]

SyntaxError: unexpected character after line continuation character (<ipython-input-61-86b335a3727a>, line 1)

In [62]:
df.iloc[1:7, 0:2]

continent  brand
1          2      3
2          2      2
3          1      1
4          2      2
5          2      2
6          2      2

In [63]:
df.at[5, 'price']

'129'

In [64]:
df.at[5, 'price']

'129'

In [65]:
df.at[6, 'price']

'155'

In [66]:
case=data.copy()
case

NameError: name 'data' is not defined

In [67]:
case=df.copy()
case

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [68]:
case.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [69]:
case.rename(columns={perid:time}, inplace=true)

NameError: name 'perid' is not defined

In [70]:
case.rename(columns={period:time}, inplace=true)

NameError: name 'period' is not defined

In [71]:
case.rename(columns={'period':'time'}, inplace=True)

In [72]:
case

continent  brand  size   time price
0           2      2  10.7  47.65   144
1           2      3  14.0  63.13   215
2           2      2   9.0  58.76   105
3           1      1   8.0  34.88    69
4           2      2  10.0  55.53   134
..        ...    ...   ...    ...   ...
58          1      1   5.0  16.66  21.5
59          2      1  21.0  43.00      
60          2      2   5.0  12.00      
61          2      3  13.0  20.00      
62          2      3  31.0  19.00      

[63 rows x 5 columns]

In [73]:
case.rename(columns={'time':'period'}, inplace=True)
case

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [74]:
case.rename(columns={'period':'time'}, inplace=True)
case

continent  brand  size   time price
0           2      2  10.7  47.65   144
1           2      3  14.0  63.13   215
2           2      2   9.0  58.76   105
3           1      1   8.0  34.88    69
4           2      2  10.0  55.53   134
..        ...    ...   ...    ...   ...
58          1      1   5.0  16.66  21.5
59          2      1  21.0  43.00      
60          2      2   5.0  12.00      
61          2      3  13.0  20.00      
62          2      3  31.0  19.00      

[63 rows x 5 columns]

In [75]:
case['Growth']=data['size']/data['time']
case

NameError: name 'data' is not defined

In [76]:
case['Growth']=case['size']/case['time']
case

continent  brand  size   time price    Growth
0           2      2  10.7  47.65   144  0.224554
1           2      3  14.0  63.13   215  0.221765
2           2      2   9.0  58.76   105  0.153165
3           1      1   8.0  34.88    69  0.229358
4           2      2  10.0  55.53   134  0.180083
..        ...    ...   ...    ...   ...       ...
58          1      1   5.0  16.66  21.5  0.300120
59          2      1  21.0  43.00        0.488372
60          2      2   5.0  12.00        0.416667
61          2      3  13.0  20.00        0.650000
62          2      3  31.0  19.00        1.631579

[63 rows x 6 columns]

In [77]:
del case['Growth']
case

continent  brand  size   time price
0           2      2  10.7  47.65   144
1           2      3  14.0  63.13   215
2           2      2   9.0  58.76   105
3           1      1   8.0  34.88    69
4           2      2  10.0  55.53   134
..        ...    ...   ...    ...   ...
58          1      1   5.0  16.66  21.5
59          2      1  21.0  43.00      
60          2      2   5.0  12.00      
61          2      3  13.0  20.00      
62          2      3  31.0  19.00      

[63 rows x 5 columns]

In [78]:
new=case[(case['continent']==1)& (case['brand']==1)]

In [79]:
new

continent  brand  size   time price
3           1      1   8.0  34.88    69
11          1      1  10.4  17.67    54
12          1      1   7.4  16.41    39
13          1      1   5.4  12.02  29.5
16          1      1   6.0  23.21    42
17          1      1   9.0  28.64    65
19          1      1  12.4  23.77  49.5
20          1      1   7.5  20.21  36.5
22          1      1   7.0  17.84    45
25          1      1   5.5  15.61    30
42          1      1  10.0  31.86  43.5
47          1      1   8.0  21.34    42
53          1      1   8.5  30.20  54.5
54          1      1   6.0  20.85  24.5
58          1      1   5.0  16.66  21.5

In [80]:
new2=case[(case['continent']==1)&(case['brand']==1)]
new2

continent  brand  size   time price
3           1      1   8.0  34.88    69
11          1      1  10.4  17.67    54
12          1      1   7.4  16.41    39
13          1      1   5.4  12.02  29.5
16          1      1   6.0  23.21    42
17          1      1   9.0  28.64    65
19          1      1  12.4  23.77  49.5
20          1      1   7.5  20.21  36.5
22          1      1   7.0  17.84    45
25          1      1   5.5  15.61    30
42          1      1  10.0  31.86  43.5
47          1      1   8.0  21.34    42
53          1      1   8.5  30.20  54.5
54          1      1   6.0  20.85  24.5
58          1      1   5.0  16.66  21.5

In [81]:
new3= case[(case['continent']==1)&(case['brand']==1)]
new3 

continent  brand  size   time price
3           1      1   8.0  34.88    69
11          1      1  10.4  17.67    54
12          1      1   7.4  16.41    39
13          1      1   5.4  12.02  29.5
16          1      1   6.0  23.21    42
17          1      1   9.0  28.64    65
19          1      1  12.4  23.77  49.5
20          1      1   7.5  20.21  36.5
22          1      1   7.0  17.84    45
25          1      1   5.5  15.61    30
42          1      1  10.0  31.86  43.5
47          1      1   8.0  21.34    42
53          1      1   8.5  30.20  54.5
54          1      1   6.0  20.85  24.5
58          1      1   5.0  16.66  21.5

In [82]:
new4=case[(case['size']>=10)&(case['period']>=30)]
new4

KeyError: 'period'

In [83]:
new4=case[(case['size']>=10)&(case['time']>=30)]
new4

continent  brand  size    time price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
4           2      2  10.0   55.53   134
5           2      2  10.5   43.14   129
6           2      2  16.0   54.86   155
7           2      1  15.0   44.14    99
10          2      2  25.0  109.38   260
14          2      2  15.4   49.48   109
15          2      1  12.4   48.74  89.5
21          1      3  14.0   32.62   109
27          1      3  12.0   45.78   119
29          1      3  14.2   37.11   109
30          2      2  11.0   45.12    99
32          2      3  13.5   68.63   179
33          2      2  11.1   33.71    99
36          2      3  13.0   86.42   199
37          1      3  13.0   39.71    93
39          2      2  12.3   33.89    74
40          2      3  19.5   64.30   165
42          1      1  10.0   31.86  43.5
43          1      3  11.0   53.18    94
44          2      3  17.8   74.48   189
45          2      2  11.5   34.16    75
46          2      1  12.7   31.46  59.5
50          2      2  14.0   33.70    99
51          2      2  12.4   32.90    89
59          2      1  21.0   43.00

In [84]:
df['brand'].value_counts()

2    24
1    23
3    16
Name: brand, dtype: int64

In [85]:
replace_barnd={'brand': {1:1, 2:1, 3:2}}
df_rocode1=df.replace(recode_brand)
df_recode1.head()

NameError: name 'recode_brand' is not defined

In [86]:
replace_barnd={'brand': {1:1, 2:1, 3:2}}
df_recode1=df.replace(recode_brand)
df_recode1.head()

NameError: name 'recode_brand' is not defined

In [87]:
replace_barnd={'brand': {1:1, 2:1, 3:2}}
df_recode1=df.replace(replace_barnd)
df_recode1.head()

continent  brand  size  period price
0          2      1  10.7   47.65   144
1          2      2  14.0   63.13   215
2          2      1   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      1  10.0   55.53   134

In [88]:
#하위변수 줄이는 방법 생각보다 까다롭다. 1.셋트를사용해서 키값과 발류값 새롭게 지정후. 2. 이셋트를 사용해서  replace함수를 사용한다. 

In [89]:
df_recode['brand'].value_counts()

NameError: name 'df_recode' is not defined

In [90]:
df_recode1['brand'].value_counts()

1    47
2    16
Name: brand, dtype: int64

In [91]:
def brand_groups(series):
    if seires==1:
        return 1
    elif seires==2:
        return 1
    elif series==3:
        return 2

df['re_brand']=df['brand'].apply(brand_groups)
df.head()

NameError: name 'seires' is not defined

In [92]:
def brand_groups(series):
    if series==1:
        return 1
    elif series==2:
        return 1
    elif series==3:
        return 2

df['re_brand']=df['brand'].apply(brand_groups)
df.head()

continent  brand  size  period price  re_brand
0          2      2  10.7   47.65   144         1
1          2      3  14.0   63.13   215         2
2          2      2   9.0   58.76   105         1
3          1      1   8.0   34.88    69         1
4          2      2  10.0   55.53   134         1

In [93]:
df.head()

continent  brand  size  period price  re_brand
0          2      2  10.7   47.65   144         1
1          2      3  14.0   63.13   215         2
2          2      2   9.0   58.76   105         1
3          1      1   8.0   34.88    69         1
4          2      2  10.0   55.53   134         1

In [94]:
del df['re_brand']
df.head()

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [95]:
df_num=df.to=numpy()
df_num

NameError: name 'numpy' is not defined

In [96]:
df_num=df.to_numpy()
df_num

array([[2, 2, 10.7, 47.65, '144'],
       [2, 3, 14.0, 63.13, '215'],
       [2, 2, 9.0, 58.76, '105'],
       [1, 1, 8.0, 34.88, '69'],
       [2, 2, 10.0, 55.53, '134'],
       [2, 2, 10.5, 43.14, '129'],
       [2, 2, 16.0, 54.86, '155'],
       [2, 1, 15.0, 44.14, '99'],
       [2, 1, 6.5, 17.46, '38.5'],
       [2, 1, 5.0, 21.04, '36.5'],
       [2, 2, 25.0, 109.38, '260'],
       [1, 1, 10.4, 17.67, '54'],
       [1, 1, 7.4, 16.41, '39'],
       [1, 1, 5.4, 12.02, '29.5'],
       [2, 2, 15.4, 49.48, '109'],
       [2, 1, 12.4, 48.74, '89.5'],
       [1, 1, 6.0, 23.21, '42'],
       [1, 1, 9.0, 28.64, '65'],
       [1, 3, 9.0, 44.95, '115'],
       [1, 1, 12.4, 23.77, '49.5'],
       [1, 1, 7.5, 20.21, '36.5'],
       [1, 3, 14.0, 32.62, '109'],
       [1, 1, 7.0, 17.84, '45'],
       [1, 2, 9.0, 22.82, '58'],
       [1, 2, 12.0, 29.48, '89'],
       [1, 1, 5.5, 15.61, '30'],
       [1, 2, 6.0, 13.25, '31'],
       [1, 3, 12.0, 45.78, '119'],
       [2, 1, 5.5, 26.53, '22'],
     

In [97]:
df_pd = pd.DataFrame(df_num)
df_pd.head()

0  1     2      3    4
0  2  2  10.7  47.65  144
1  2  3  14.0  63.13  215
2  2  2   9.0  58.76  105
3  1  1   8.0  34.88   69
4  2  2  10.0  55.53  134

In [98]:
df_pd2= pd.DataFrame(data = df_num, columns=['continent', 'brand','size','period','price'])
df_pd2.head()

continent brand  size period price
0         2     2  10.7  47.65   144
1         2     3  14.0  63.13   215
2         2     2   9.0  58.76   105
3         1     1   8.0  34.88    69
4         2     2  10.0  55.53   134