In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('breast-cancer-wisconsin.csv', encoding='euc-kr')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [2]:
X=data[data.columns[1:9]]
y=data[['Class']]


In [3]:
from sklearn.model_selction import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, strtify=y)

ModuleNotFoundError: No module named 'sklearn.model_selction'

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, strtify=y)

TypeError: train_test_split() got an unexpected keyword argument 'strtify'

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, stratify=y)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_sc_train=scaler.transform(X_train)
X_sc_test=scaler.transform(X_test)


In [7]:
X_sc_train

array([[ 1.26858824,  2.24642533,  0.59623419, ...,  0.12639921,
         0.2390748 ,  2.33579096],
       [-0.86330622, -0.69518533, -0.40465731, ..., -0.69976755,
        -0.17168459, -0.61468183],
       [-0.15267473,  0.28535155,  0.26260369, ..., -0.14898971,
        -0.58244397, -0.61468183],
       ...,
       [-0.86330622, -0.69518533, -0.7382878 , ..., -0.69976755,
        -0.17168459, -0.61468183],
       [ 0.20264101,  2.24642533,  2.26438669, ...,  1.77873274,
         1.06059357,  0.69663941],
       [-0.50799048, -0.69518533, -0.7382878 , ..., -0.69976755,
        -0.58244397, -0.61468183]])

In [8]:
X_sc_test

array([[-0.15267473, -0.69518533, -0.7382878 , ..., -0.69976755,
        -0.58244397, -0.61468183],
       [ 1.97921973,  2.24642533,  0.92986469, ...,  1.77873274,
         0.2390748 ,  0.04097879],
       [-0.15267473, -0.69518533, -0.7382878 , ..., -0.69976755,
        -0.58244397, -0.61468183],
       ...,
       [ 1.26858824,  0.28535155,  0.26260369, ...,  1.50334382,
        -0.17168459,  0.04097879],
       [-0.50799048, -0.3683397 , -0.40465731, ..., -0.69976755,
        -0.17168459, -0.28685152],
       [ 0.20264101, -0.69518533, -0.7382878 , ..., -0.69976755,
        -0.17168459, -0.61468183]])

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_sc_train, y_train)
rf_train_predict=rf.predict(X_sc_train)
print("RandomForest Train {:.4f}".format(rf.score(X_sc_train, y_train)))

RandomForest Train 1.0000


In [10]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_sc_train, y_train)
rf_train_predict=rf.predict(X_sc_train)
print("RandomForest Train : {:.4f}".format(rf.score(X_sc_train, y_train)))

RandomForest Train : 1.0000


In [11]:
from sklearn.metrics import confusion_matrix
rf_confusion=confusion_matrix(rf_train_predict, y_train)
print("RandomForest Train's Confusion Matrix= \n", rf_confusion)

RandomForest Train's Confusion Matrix= 
 [[333   0]
 [  0 179]]


In [12]:
from sklearn.metrics import confusion_matrix
rf_confusion=confusion_matrix(rf_train_predict, y_train)
print("RandomForest Train's Confusion Matrix \n", rf_confusion

SyntaxError: unexpected EOF while parsing (<ipython-input-12-d0a5d2a8e4e4>, line 3)

In [13]:
from sklearn.metrics import confusion_matrix
rf_confusion=confusion_matrix(rf_train_predict, y_train)
print("RandomForest Train's Confusion Matrix \n", rf_confusion)

RandomForest Train's Confusion Matrix 
 [[333   0]
 [  0 179]]


In [14]:
from sklearn.metrcis import classification_report
cfreport_rf_train=classification_report(y_train, rf_train_predict)
print('RandomForest Train Classification Report \n", cfreport_rf_train)

SyntaxError: EOL while scanning string literal (<ipython-input-14-a4c5b6dfa644>, line 3)

In [15]:
from sklearn.metrcis import classification_report
cfreport_rf_train=classification_report(y_train, rf_train_predict)
print('RandomForest Train Classification Report \n', cfreport_rf_train)

ModuleNotFoundError: No module named 'sklearn.metrcis'

In [16]:
from sklearn.metrics import classification_report
cfreport_rf_train=classification_report(y_train, rf_train_predict)
print('RandomForest Train Classification Report \n', cfreport_rf_train)

RandomForest Train Classification Report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [17]:
rf_test_predict=rf.predict(X_sc_test)
rf.score(X_sc_test, y_test)


0.9824561403508771

In [18]:
rf_confusion_test=confusion_matrix(y_test, rf_test_predict)


In [19]:
rf_confusion_test

array([[109,   2],
       [  1,  59]])

In [20]:
print("RF TesT Confusion Matrix \n", rf_confusion_test)

RF TesT Confusion Matrix 
 [[109   2]
 [  1  59]]


In [21]:
data.head()

code  Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0  1000025                5          1           1                  1   
1  1002945                5          4           4                  5   
2  1015425                3          1           1                  1   
3  1016277                6          8           8                  1   
4  1017023                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  Class  
0        1      0  
1        1      0  
2        1      0  
3        1      0  
4        1      0

In [22]:
param_grid={'n_estimators': range(100, 1000, 100),
           'max_features': ['auto', 'sqrt', 'log2']}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(RandomForestClassifier(), param_grid, cv=5)
grid_search.fit(X_sc_train, y_train)


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': range(100, 1000, 100)})

In [23]:
print(" Best Paramter: {}".format(grid_search.best_params_))
print("Best Score: {:.4f}".format(grid_search.best_score_))
print("Test set Score {:.4f}".format(grid_search.score(X_sc_test, y_test)))


 Best Paramter: {'max_features': 'auto', 'n_estimators': 700}
Best Score: 0.9746
Test set Score 0.9825


In [24]:
from scipy.stas import randint
param_distribs = {'n_estimators': randint(low=100, high=1000),
                 'max_features':['auto','sqrt','log2']}
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(RandomForestClassifier(),
                                param_distributions=param_distribs, n_iter=20, cv=5)
random_search.fit(X_sc_train, y_train)



ModuleNotFoundError: No module named 'scipy.stas'

In [25]:
from scipy.stats import randint
param_distribs = {'n_estimators': randint(low=100, high=1000),
                 'max_features':['auto','sqrt','log2']}
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(RandomForestClassifier(),
                                param_distributions=param_distribs, n_iter=20, cv=5)
random_search.fit(X_sc_train, y_train)



RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=20,
                   param_distributions={'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fd424944d30>})

In [26]:
print('Best Parameter: {}'.format(random_search.best_params_))
print('Best Score: {:.4f}'.format(random_search.best_score_))
print('Test Set score: {:.4f}'.format(random_search.score(X_sc_test, y_test)))


Best Parameter: {'max_features': 'sqrt', 'n_estimators': 790}
Best Score: 0.9746
Test Set score: 0.9825


In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [28]:
model_lr=LogisticRegression(random_state=42)
model_svc=SVC(random_state=42)
model_rf=RandomForestClassifier(random_state=42)


In [29]:
voting_hard=VotingClassifier(esitimators=[('lr',model_lr), ('rf', model_rf), ('svc',model_svc)],
                            voting='hard')
voting_hard.fit(X_scaled_train, y_train)


TypeError: __init__() got an unexpected keyword argument 'esitimators'

In [30]:
voting_hard=VotingClassifier(estimators=[('lr',model_lr), ('rf', model_rf), ('svc',model_svc)],
                            voting='hard')
voting_hard.fit(X_scaled_train, y_train)



NameError: name 'X_scaled_train' is not defined

In [31]:
voting_hard=VotingClassifier(estimators=[('lr',model_lr), ('rf', model_rf), ('svc',model_svc)],
                            voting='hard')
voting_hard.fit(X_sc_train, y_train)



VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [32]:
from sklearn.metrics import accuracy_score

for clf in (model_lr, model_svc, model_rf, voting_hard):
    clf.fit(X_sc_train, y_train)
    y_pred = clf.predict(X_sc_test)
    print(clf._class_._name_, accuracy_score(y_test, y_pred))
    

AttributeError: 'LogisticRegression' object has no attribute '_class_'

In [33]:
from sklearn.metrics import accuracy_score

for clf in (model_lr, model_svc, model_rf, voting_hard):
    clf.fit(X_sc_train, y_train)
    y_pred = clf.predict(X_sc_test)
    print(clf.__class__._name_, accuracy_score(y_test, y_pred))

AttributeError: type object 'LogisticRegression' has no attribute '_name_'

In [34]:
from sklearn.metrics import accuracy_score

for clf in (model_lr, model_svc, model_rf, voting_hard):
    clf.fit(X_sc_train, y_train)
    y_pred = clf.predict(X_sc_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9824561403508771
SVC 0.9766081871345029
RandomForestClassifier 0.9824561403508771
VotingClassifier 0.9824561403508771


In [35]:
voting_soft= VotingClassifier(estimators=[('lr', model_lr), ('svc', model_svc), ('rf', model_rf)]
                             voting='soft')
voting_soft.fit(X_sc_train, y_train)


SyntaxError: invalid syntax (<ipython-input-35-7e3e642dece3>, line 2)

In [36]:
voting_soft= VotingClassifier(estimators=[('lr', model_lr), ('svc', model_svc), ('rf', model_rf)],
                             voting='soft')
voting_soft.fit(X_sc_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('svc', SVC(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42))],
                 voting='soft')

In [37]:
from sklearn. metrics import accuracy_score
for clf in (logit_model, rnf_model, svm_model, voting_soft):
    clf.fit(X_sc_train, y_train)
    y_pred=clf.predict(X_sc_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))


NameError: name 'logit_model' is not defined

In [38]:
from sklearn. metrics import accuracy_score
for clf in (model_lr, model_rf, model_svc, voting_soft):
    clf.fit(X_sc_train, y_train)
    y_pred=clf.predict(X_sc_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9824561403508771
RandomForestClassifier 0.9824561403508771
SVC 0.9766081871345029


AttributeError: predict_proba is not available when  probability=False

In [39]:
from sklearn.metrics import accuracy_score

for clf in (model_lr, model_svc, model_rf, voting_soft):
    clf.fit(X_sc_train, y_train)
    y_pred = clf.predict(X_sc_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9824561403508771
SVC 0.9766081871345029
RandomForestClassifier 0.9824561403508771


AttributeError: predict_proba is not available when  probability=False

In [40]:
model_lr= LogisticRegression(random_state=42)
model_rf= RandomForestClassifier(random_state=42)
model_svc= SVC(probability=True, random_state=42)
voting_soft= VotingClassifier(estimators=[('lr', model_lr), ('rf',model_rf), ('svc',model_svc)],
                             voting='soft')
voting_soft.fit(X_sc_train, y_train)


VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(probability=True, random_state=42))],
                 voting='soft')

In [41]:
from sklearn.metrics import accuracy_score

for clf in (model_lr, model_svc, model_rf, voting_soft):
    clf.fit(X_sc_train, y_train)
    y_pred = clf.predict(X_sc_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9824561403508771
SVC 0.9766081871345029
RandomForestClassifier 0.9824561403508771
VotingClassifier 0.9766081871345029


In [42]:
voting_pred_trian=voting_soft.predict(X_sc_train)
voting_confusion_train=cnfusion_matrix(y_train, voting_pred_train)
voting_confusion_train

NameError: name 'cnfusion_matrix' is not defined

In [43]:
voting_pred_trian=voting_soft.predict(X_sc_train)
voting_confusion_train=confusion_matrix(y_train, voting_pred_train)
voting_confusion_train

NameError: name 'voting_pred_train' is not defined

In [44]:
voting_pred_train=voting_soft.predict(X_sc_train)
voting_confusion_train=confusion_matrix(y_train, voting_pred_train)
voting_confusion_train

array([[325,   8],
       [  2, 177]])

In [45]:
voting_pred_train=voting_soft.predict(X_sc_train)
voting_confusion_train=confusion_matrix(y_train, voting_pred_train)
print('voting confusion train \n',voting_confusion_train)

voting confusion train 
 [[325   8]
 [  2 177]]


In [46]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= baggingClassifierbase_estimator=SVC(), n_estimators=10, random_state=42)
model.fit(X_scaled_train, y_train)
pred_trian= model.predcit(X_sc_train)
model.score(X_sc_train, y_train)


SyntaxError: unmatched ')' (<ipython-input-46-257c00fe3fdf>, line 3)

In [47]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=42)
model.fit(X_scaled_train, y_train)
pred_trian= model.predcit(X_sc_train)
model.score(X_sc_train, y_train)



NameError: name 'X_scaled_train' is not defined

In [48]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=42)
model.fit(X_sc_train, y_train)
pred_trian= model.predcit(X_sc_train)
model.score(X_sc_train, y_train)

AttributeError: 'BaggingClassifier' object has no attribute 'predcit'

In [49]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=42)
model.fit(X_sc_train, y_train)
pred_train= model.predict(X_sc_train)
model.score(X_sc_train, y_train)

0.970703125

In [50]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
confusion_train

array([[325,   8],
       [  7, 172]])

In [51]:
from sklearn.metrics import classifcaion_report
cf_report_train=classifcaion_report(y_train, pred_train)
cf_report_train

ImportError: cannot import name 'classifcaion_report' from 'sklearn.metrics' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [52]:
from sklearn.metrics import classificaion_report
cf_report_train=classificaion_report(y_train, pred_train)
cf_report_train

ImportError: cannot import name 'classificaion_report' from 'sklearn.metrics' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [53]:
from sklearn.metrics import classification_report
cf_report_train=classificaion_report(y_train, pred_train)
cf_report_train

NameError: name 'classificaion_report' is not defined

In [54]:
from sklearn.metrics import classification_report
cf_report_train=classification_report(y_train, pred_train)
cf_report_train

'              precision    recall  f1-score   support\n\n           0       0.98      0.98      0.98       333\n           1       0.96      0.96      0.96       179\n\n    accuracy                           0.97       512\n   macro avg       0.97      0.97      0.97       512\nweighted avg       0.97      0.97      0.97       512\n'

In [55]:
from sklearn.metrics import classification_report
cf_report_train=classification_report(y_train, pred_train)
print(cf_report_train)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       333
           1       0.96      0.96      0.96       179

    accuracy                           0.97       512
   macro avg       0.97      0.97      0.97       512
weighted avg       0.97      0.97      0.97       512



In [56]:
cfreport_test=classification_report(y_test, pred_test)
print(cfreport_test)

NameError: name 'pred_test' is not defined

In [57]:
pred_test=model.predict(X_sc_test)


In [58]:
cfreport_test=classification_report(y_test, pred_test)
print(cfreport_test)

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       111
           1       0.97      0.98      0.98        60

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



In [59]:
from sklearn.ensemble import AdaboostClassifier
model = AdaBoostClassifier(n_estimators=100, random_state=42)
model.fit(X_sc_train, y_train)
pred_train=model.predict(X_sc_train)
model.score(X_xc_train, y_train)


ImportError: cannot import name 'AdaboostClassifier' from 'sklearn.ensemble' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/__init__.py)

In [60]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(n_estimators=100, random_state=42)
model.fit(X_sc_train, y_train)
pred_train=model.predict(X_sc_train)
model.score(X_xc_train, y_train)

NameError: name 'X_xc_train' is not defined

In [61]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(n_estimators=100, random_state=42)
model.fit(X_sc_train, y_train)
pred_train=model.predict(X_sc_train)
model.score(X_sc_train, y_train)

1.0

In [62]:
confusion_ada_train=confusion_matrix(pred_train, y_train)
print("Confusion Adaboost Train", confusion_ada_train)

Confusion Adaboost Train [[333   0]
 [  0 179]]


In [63]:
cfreport_ada_train=classification_report(pred_train, y_train)


In [64]:
print("cfreport Adaboost Train", cfreport_ada_train)

cfreport Adaboost Train               precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [65]:
pred_test=model.predict(X_sc_test)
model.score(X_sc_test, y_test)


0.9590643274853801

In [66]:
from sklearn.ensemble import GradientBoostingClassifier
model= GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=42)
model.fit(X_sc_train, y_train)
pred_train=model.predict(X_sc_train)
model.score(X_sc_train, y_train)


0.99609375

In [67]:
pred_test= model.predict(X_sc_test)
model.score(X_sc_test, y_test)


0.9649122807017544

In [68]:
from sklearn.ensmelbe import StackingClassifier
estimators= [('rf', RandomForestClassifier(n_estimators=10, random_state=42)), ('svc', SVC(random_state=42))]
model= StackingClassifier(esimators=estimators, final_estimator=LogisticRegression())
model.fit(X_sc_train, y_train)
pred_train= model.predict(X_sc_train)
model.score(X_sc_train, y_train)


ModuleNotFoundError: No module named 'sklearn.ensmelbe'

In [69]:
from sklearn.ensemlbe import StackingClassifier
estimators= [('rf', RandomForestClassifier(n_estimators=10, random_state=42)), ('svc', SVC(random_state=42))]
model= StackingClassifier(esimators=estimators, final_estimator=LogisticRegression())
model.fit(X_sc_train, y_train)
pred_train= model.predict(X_sc_train)
model.score(X_sc_train, y_train)



ModuleNotFoundError: No module named 'sklearn.ensemlbe'

In [70]:
from sklearn.ensemble import StackingClassifier
estimators= [('rf', RandomForestClassifier(n_estimators=10, random_state=42)), ('svc', SVC(random_state=42))]
model= StackingClassifier(esimators=estimators, final_estimator=LogisticRegression())
model.fit(X_sc_train, y_train)
pred_train= model.predict(X_sc_train)
model.score(X_sc_train, y_train)



TypeError: __init__() got an unexpected keyword argument 'esimators'

In [71]:
from sklearn.ensemble import StackingClassifier
estimators= [('rf', RandomForestClassifier(n_estimators=10, random_state=42)), ('svc', SVC(random_state=42))]
model= StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
model.fit(X_sc_train, y_train)
pred_train= model.predict(X_sc_train)
model.score(X_sc_train, y_train)

0.978515625

In [72]:
pred_test=model.predcit(X_sc_test)
model.score(X_sc_test, y_test)


AttributeError: 'StackingClassifier' object has no attribute 'predcit'

In [73]:
pred_test=model.predict(X_sc_test)
model.score(X_sc_test, y_test)



0.9766081871345029

In [74]:
stacking_confusion_test=confusion_matrix(y_test, pred_test)
print(stacking_confusion_test)

[[108   3]
 [  1  59]]


In [75]:
stacking_confusion_train=confusion_matrix(y_train, pred_train)
print(stacking_confusion_train)

[[325   8]
 [  3 176]]


In [76]:
stacking_cfreport_test=classification_report(y_test, pred_test)
print(stacking_cfreport_test)

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       111
           1       0.95      0.98      0.97        60

    accuracy                           0.98       171
   macro avg       0.97      0.98      0.97       171
weighted avg       0.98      0.98      0.98       171



In [77]:
stacking_cfreport_train=classification_report(y_train, pred_train)
print(stacking_cfreport_train)

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       333
           1       0.96      0.98      0.97       179

    accuracy                           0.98       512
   macro avg       0.97      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512

