In [2]:
#1 분석데이터유지 


In [3]:
import warnings 
warnings.filterwarnings("ignore")
import pandas as pd
data=pd.read_csv("breast-cancer-wisconsin.csv")
data.info()
data.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


code  Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0  1000025                5          1           1                  1   
1  1002945                5          4           4                  5   
2  1015425                3          1           1                  1   
3  1016277                6          8           8                  1   
4  1017023                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  Class  
0        1      0  
1        1      0  
2        1      0  
3        1      0  
4        1      0

In [4]:
X=data[data.columns[1:10]]
y=data[['Class']]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, stratify=y, random_state=42)

In [6]:
from sklearn.model_selection import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaeld_test=scaler.transform(X_train)


ImportError: cannot import name 'MinMaxScaler' from 'sklearn.model_selection' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/__init__.py)

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaeld_test=scaler.transform(X_train)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.lineal_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

logit_model=LogisticRegression(random_state=42)
rmf_model=RandomForestClassifier(random_state=42)
svm_model=SVC(random_state=42)

voting_hard=VotingClassifier(
estimators=[('lr', logit_model), ('rf', rnf_model), ('svc', svm_model)],
voting='hard')
voting_hard.fit(X_scaled_train, y_train)


ModuleNotFoundError: No module named 'sklearn.lineal_model'

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

logit_model=LogisticRegression(random_state=42)
rmf_model=RandomForestClassifier(random_state=42)
svm_model=SVC(random_state=42)

voting_hard=VotingClassifier(
estimators=[('lr', logit_model), ('rf', rnf_model), ('svc', svm_model)],
voting='hard')
voting_hard.fit(X_scaled_train, y_train)



NameError: name 'rnf_model' is not defined

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

logit_model=LogisticRegression(random_state=42)
rf_model=RandomForestClassifier(random_state=42)
svm_model=SVC(random_state=42)

voting_hard=VotingClassifier(
estimators=[('lr', logit_model), ('rf', rf_model), ('svc', svm_model)],
voting='hard')
voting_hard.fit(X_scaled_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [11]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rf_model, svm_model, voting_hard):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predict(X_scaled_test)
    print(clf._class_._name_, accuracy_score(y_test, y_pred))
    

NameError: name 'X_scaled_test' is not defined

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_train)

In [13]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rf_model, svm_model, voting_hard):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predict(X_scaled_test)
    print(clf._class_._name_, accuracy_score(y_test, y_pred))

AttributeError: 'LogisticRegression' object has no attribute '_class_'

In [14]:
from sklearn.metrics import accuracy_score

for clf in (logit_model, rf_model, svm_model, voting_hard):
    clf.fit(X_scaled_train, y_train)
    y_pred = clf.predict(X_scaled_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [171, 512]

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

logit_model= LogisticRegression(random_state=42)
rnf_model = RandomForestClassifier(random_state=42)
svm_model = SVC(random_state=42)

voting_hard = VotingClassifier(
    estimators=[('lr', logit_model), ('rf', rnf_model), ('svc', svm_model)], voting='hard')
voting_hard.fit(X_scaled_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [16]:
from sklearn.metrics import accuracy_score

for clf in (logit_model, rnf_model, svm_model, voting_hard):
    clf.fit(X_scaled_train, y_train)
    y_pred = clf.predict(X_scaled_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [171, 512]

In [17]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
data1=pd.read_csv('breast-cancer-wisconsin.csv', encoding='utf-8')
X=data1[data1.columns[1:10]]
y=data1[["Class"]]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, stratify=y, random_state=42)

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

logit_model= LogisticRegression(random_state=42)
rnf_model = RandomForestClassifier(random_state=42)
svm_model = SVC(random_state=42)

voting_hard = VotingClassifier(
    estimators=[('lr', logit_model), ('rf', rnf_model), ('svc', svm_model)], voting='hard')
voting_hard.fit(X_scaled_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [21]:
from sklearn.metrics import accuracy_score

for clf in (logit_model, rnf_model, svm_model, voting_hard):
    clf.fit(X_scaled_train, y_train)
    y_pred = clf.predict(X_scaled_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9590643274853801
RandomForestClassifier 0.9649122807017544
SVC 0.9649122807017544
VotingClassifier 0.9649122807017544


In [22]:
from sklearn.metrics import confusion_matrix
log_pred_train=logit_mdoel.predict(X_scaled_train)
log_confusion_train=confusion_matrix(y_traiin. log_pred_train)
print("로지스틱 분류기 훈련데이터 오차행렬:\n", log_confusion_train)
log_pred_test=logit_model.predict(X_scaled_test)
logit_confusion_test=confusion_matrix(y_test, log_pred_test)
print("로지스틱 분류기 테스트데이터 오차행렬:\n", log_confusion_test)


NameError: name 'logit_mdoel' is not defined

In [23]:
from sklearn.metrics import confusion_matrix
log_pred_train=logit_model.predict(X_scaled_train)
log_confusion_train=confusion_matrix(y_traiin. log_pred_train)
print("로지스틱 분류기 훈련데이터 오차행렬:\n", log_confusion_train)
log_pred_test=logit_model.predict(X_scaled_test)
logit_confusion_test=confusion_matrix(y_test, log_pred_test)
print("로지스틱 분류기 테스트데이터 오차행렬:\n", log_confusion_test)

NameError: name 'y_traiin' is not defined

In [24]:
from sklearn.metrics import confusion_matrix
log_pred_train=logit_model.predict(X_scaled_train)
log_confusion_train=confusion_matrix(y_train. log_pred_train)
print("로지스틱 분류기 훈련데이터 오차행렬:\n", log_confusion_train)
log_pred_test=logit_model.predict(X_scaled_test)
logit_confusion_test=confusion_matrix(y_test, log_pred_test)
print("로지스틱 분류기 테스트데이터 오차행렬:\n", log_confusion_test)

AttributeError: 'DataFrame' object has no attribute 'log_pred_train'

In [25]:
from sklearn.metrics import confusion_matrix
log_pred_train=logit_model.predict(X_scaled_train)
log_confusion_train=confusion_matrix(y_train, log_pred_train)
print("로지스틱 분류기 훈련데이터 오차행렬:\n", log_confusion_train)
log_pred_test=logit_model.predict(X_scaled_test)
logit_confusion_test=confusion_matrix(y_test, log_pred_test)
print("로지스틱 분류기 테스트데이터 오차행렬:\n", log_confusion_test)

로지스틱 분류기 훈련데이터 오차행렬:
 [[328   5]
 [  9 170]]


NameError: name 'log_confusion_test' is not defined

In [26]:
log_pred_test=logit_model.predict(X_scaled_test)
log_confusion_test=confusion_matrix(y_test, log_pred_test)
print("로지스틱 분류기 테스트데이터 오차행렬:\n", log_confusion_test)

로지스틱 분류기 테스트데이터 오차행렬:
 [[106   5]
 [  2  58]]


In [27]:
svm_pred_train=svm_model.predict(X_scaled_train)
svm_confusion_train=confusion_matrix(y_train, svm_pred_train)
print("SVM Train Data CM:\n", svm_confusion_train)
svm_pred_test=svm_mdoel.predict(X_scaled_test)
svm_confusion_test=confusion_matrix(y_test, svm_pred_test)
print("SVM TEST Data cm:\n", svm_confusion_test)


SVM Train Data CM:
 [[329   4]
 [  4 175]]


NameError: name 'svm_mdoel' is not defined

In [28]:
svm_pred_train=svm_model.predict(X_scaled_train)
svm_confusion_train=confusion_matrix(y_train, svm_pred_train)
print("SVM Train Data CM:\n", svm_confusion_train)
svm_pred_test=svm_model.predict(X_scaled_test)
svm_confusion_test=confusion_matrix(y_test, svm_pred_test)
print("SVM TEST Data cm:\n", svm_confusion_test)

SVM Train Data CM:
 [[329   4]
 [  4 175]]
SVM TEST Data cm:
 [[106   5]
 [  1  59]]


In [29]:
rnd_pred_train=rnf_model.predict(X_scaled_train)
rnd_confusion_train=confusion_matrix(y_train, rnd_pred_train)
print("RF TrainD CM:\n", rnd_confusion_train)
rnd_pred_test=rnf_mdoel.predict(X_scaled_test)
rnd_confusion_test=confusion_matrix(y_test, rnd_pred_test)
print("RF TestD CM:\n", rnd_confsuion_test)


RF TrainD CM:
 [[333   0]
 [  0 179]]


NameError: name 'rnf_mdoel' is not defined

In [30]:
rnd_pred_train=rnf_model.predict(X_scaled_train)
rnd_confusion_train=confusion_matrix(y_train, rnd_pred_train)
print("RF TrainD CM:\n", rnd_confusion_train)
rnd_pred_test=rnf_model.predict(X_scaled_test)
rnd_confusion_test=confusion_matrix(y_test, rnd_pred_test)
print("RF TestD CM:\n", rnd_confsuion_test)

RF TrainD CM:
 [[333   0]
 [  0 179]]


NameError: name 'rnd_confsuion_test' is not defined

In [31]:
rnd_pred_test=rnf_model.predict(X_scaled_test)
rnd_confusion_test=confusion_matrix(y_test, rnd_pred_test)
print("랜덤포레스트 분류기 테스트데이터 오차행렬:\n", rnd_confusion_test)

랜덤포레스트 분류기 테스트데이터 오차행렬:
 [[106   5]
 [  1  59]]


In [32]:
rnd_pred_test=rnf_model.predict(X_scaled_test)
rnd_confusion_test=confusion_matrix(y_test, rnd_pred_test)
print("RF TestD CM:\n", rnd_confusion_test)

RF TestD CM:
 [[106   5]
 [  1  59]]


In [33]:
voting_pred_train=voting_hard.predict(X_scaled_train)
voting_confusin_train=confusion_matrix(y_train, voting_pred_train)
print("투표분류기 분류기 훈련데이터 오차행렬:\n", voting_confusion_train)
voting_pred_test=voting_hard.predict(X_scaled_test)
voting_confusion_test=confusion_matrix(y_test, voting_pred_test)
print("투표분류기 분류기 테스트데이터 오차행렬:\n", voting_confusion_test)


NameError: name 'voting_confusion_train' is not defined

In [34]:
voting_pred_train=voting_hard.predict(X_scaled_train)
voting_confusion_train=confusion_matrix(y_train, voting_pred_train)
print("투표분류기 분류기 훈련데이터 오차행렬:\n", voting_confusion_train)
voting_pred_test=voting_hard.predict(X_scaled_test)
voting_confusion_test=confusion_matrix(y_test, voting_pred_test)
print("투표분류기 분류기 테스트데이터 오차행렬:\n", voting_confusion_test)

투표분류기 분류기 훈련데이터 오차행렬:
 [[329   4]
 [  4 175]]
투표분류기 분류기 테스트데이터 오차행렬:
 [[106   5]
 [  1  59]]


In [35]:
logit_model= LogisticRegression(random_state=42)
rnf_model= RandomRorestClassifier(random_state=42)
svm_mdoel=SVC(probability=True, random_state=42)
voting_soft=VotingClassifier(estimators=[('lr', logit_model), ('rf', rnf_model), ('svc',svm_mdoel)], voting='soft')
voting_soft.fit(X_scaled_train, y_train)


NameError: name 'RandomRorestClassifier' is not defined

In [36]:
logit_model= LogisticRegression(random_state=42)
rnf_model= RandomForestClassifier(random_state=42)
svm_mdoel=SVC(probability=True, random_state=42)
voting_soft=VotingClassifier(estimators=[('lr', logit_model), ('rf', rnf_model), ('svc',svm_mdoel)], voting='soft')
voting_soft.fit(X_scaled_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(probability=True, random_state=42))],
                 voting='soft')

In [37]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rnf_mdoel, svm_model, voting_soft):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predcit(X_scaled_test)
    print(clf._class_._name_, accuracy_score(y_test, y_pred))
    

NameError: name 'rnf_mdoel' is not defined

In [38]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rnf_model, svm_model, voting_soft):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predcit(X_scaled_test)
    print(clf._class_._name_, accuracy_score(y_test, y_pred))

AttributeError: 'LogisticRegression' object has no attribute 'predcit'

In [39]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rnf_model, svm_model, voting_soft):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predict(X_scaled_test)
    print(clf._class_._name_, accuracy_score(y_test, y_pred))

AttributeError: 'LogisticRegression' object has no attribute '_class_'

In [40]:
from sklearn.metrics import accuracy_score

for clf in (logit_model, rnf_model, svm_model, voting_soft):
    clf.fit(X_scaled_train, y_train)
    y_pred = clf.predict(X_scaled_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9590643274853801
RandomForestClassifier 0.9649122807017544
SVC 0.9649122807017544
VotingClassifier 0.9649122807017544


In [41]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rnf_model, svm_model, voting_soft):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predict(X_scaled_test)
    print(clf.__class__._name__, accuracy_score(y_test, y_pred))

AttributeError: type object 'LogisticRegression' has no attribute '_name__'

In [42]:
from sklearn.metrics import accuracy_score
for clf in (logit_model, rnf_model, svm_model, voting_soft):
    clf.fit(X_scaled_train, y_train)
    y_pred=clf.predict(X_scaled_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9590643274853801
RandomForestClassifier 0.9649122807017544
SVC 0.9649122807017544
VotingClassifier 0.9649122807017544


In [43]:
voting_pred_train=voting_soft.predict(X_scaled_train)
voting_confusion_train=confusion_matrix(y_train, voting_pred_train)
print("Voting Ensemble Train Data C_Matrix: \n", voting_confusion_train)
voting_pred_test=voting_soft.predict(X_scaeld_test)
voting_confusion_test=confusion_matrix(y_test, voting_pred_test)
print("Voting Ensemble Train Data C_Matrix: \n", voting_confusion_test)


Voting Ensemble Train Data C_Matrix: 
 [[330   3]
 [  3 176]]


ValueError: Found input variables with inconsistent numbers of samples: [171, 512]

In [44]:
voting_pred_train=voting_soft.predict(X_scaled_train)
voting_confusion_train=confusion_matrix(y_train, voting_pred_train)
print("투표분류기 분류기 훈련데이터 오차행렬:\n", voting_confusion_train)

voting_pred_test=voting_soft.predict(X_scaled_test)
voting_confusion_test=confusion_matrix(y_test, voting_pred_test)
print("투표분류기 분류기 훈련데이터 오차행렬:\n", voting_confusion_test)

투표분류기 분류기 훈련데이터 오차행렬:
 [[330   3]
 [  3 176]]
투표분류기 분류기 훈련데이터 오차행렬:
 [[106   5]
 [  1  59]]


In [45]:
voting_pred_test=voting_soft.predict(X_scaeld_test)
voting_confusion_test=confusion_matrix(y_test, voting_pred_test)
print("Voting Ensemble Train Data C_Matrix: \n", voting_confusion_test)

ValueError: Found input variables with inconsistent numbers of samples: [171, 512]

In [46]:
data1=read.pd_csv('house_price.csv')
data1.info()
data1.head()


NameError: name 'read' is not defined

In [47]:
data2=pd.read_csv('house_price.csv', encoding-'utf-8')
data2.info()
data2.head()


NameError: name 'encoding' is not defined

In [48]:
data2=pd.read_csv('house_price.csv', encoding='utf-8')
data2.info()
data2.head()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


housing_age  income  bedrooms  households     rooms  house_value
0           23  6.7770  0.141112    2.442244  8.103960       500000
1           49  6.0199  0.160984    2.726688  5.752412       500000
2           35  5.1155  0.249061    1.902676  3.888078       500000
3           32  4.7109  0.231383    1.913669  4.508393       500000
4           21  4.5625  0.255583    3.092664  4.667954       500000

In [49]:
X=data[data.columns[1:5]]
y=data[['house_value']]


KeyError: "None of [Index(['house_value'], dtype='object')] are in the [columns]"

In [50]:
X=data2[data2.columns[1:5]]
y=data2[["house_value"]]

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, ramdom_state=42)

TypeError: train_test_split() got an unexpected keyword argument 'ramdom_state'

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=42)

In [53]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler
X_scaled_train=scaler.fit(X_train)
X_scaled_test=scaler.fit(X_test)


TypeError: fit() missing 1 required positional argument: 'X'

In [54]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)



TypeError: fit() missing 1 required positional argument: 'X'

In [55]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
form skelarn.ensemble import VotingRegressor
linear_model= LogisticRegression()
rnf_model=RandomForestRegressor(random_state=42)
voting_regressor= VotingRegressor(estimators=[('lr', linear_model), ('rf', rnf_model)])
voting_regressor.fit(X_scaled_test, y_train)


SyntaxError: invalid syntax (<ipython-input-56-32420778698e>, line 3)

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from skelearn.ensemble import VotingRegressor
linear_model= LogisticRegression()
rnf_model=RandomForestRegressor(random_state=42)
voting_regressor= VotingRegressor(estimators=[('lr', linear_model), ('rf', rnf_model)])
voting_regressor.fit(X_scaled_test, y_train)

ModuleNotFoundError: No module named 'skelearn'

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor
linear_model= LogisticRegression()
rnf_model=RandomForestRegressor(random_state=42)
voting_regressor= VotingRegressor(estimators=[('lr', linear_model), ('rf', rnf_model)])
voting_regressor.fit(X_scaled_test, y_train)

ValueError: The estimator LogisticRegression should be a regressor.

In [59]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor

linear_model= LinearRegression()
rnf_model = RandomForestRegressor(random_state=42)

voting_regressor = VotingRegressor(estimators=[('lr', linear_model), ('rf', rnf_model)])
voting_regressor.fit(X_scaled_train, y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('rf', RandomForestRegressor(random_state=42))])

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor
linear_model= LinearRegression()
rnf_model=RandomForestRegressor(random_state=42)
voting_regressor= VotingRegressor(estimators=[('lr', linear_model), ('rf', rnf_model)])
voting_regressor.fit(X_scaled_test, y_train)

ValueError: Found input variables with inconsistent numbers of samples: [4423, 13266]

In [61]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor

linear_model= LinearRegression()
rnf_model = RandomForestRegressor(random_state=42)

voting_regressor = VotingRegressor(estimators=[('lr', linear_model), ('rf', rnf_model)])
voting_regressor.fit(X_scaled_train, y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('rf', RandomForestRegressor(random_state=42))])

In [62]:
pred_train=voting_regressor.predict(X_scaled_train)
voting_regressor.score(X_scaled_train, y_train)


0.7962532705428835

In [63]:
pred_test=voting_regressor.predict(X_scaled_test)
voting_regressor.score(X_scaled_test, y_test)


0.5936371957936409

In [64]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE_train=mean_squared_error(y_train, pred_train)
MSE_test=mean_squared_error(y_test, pred_test)
print("훈련 데이터 RMSE:", np.sqrt(MSE_train))
print("테스트 데이터 RMSE:", np.sqrt(MSE_test))


훈련 데이터 RMSE: 43082.050654857834
테스트 데이터 RMSE: 60942.38524353489
