In [1]:
a=[1,2,3,4,5]

In [2]:
a.append(7)

In [3]:
a

[1, 2, 3, 4, 5, 7]

In [4]:
a[3]

4

In [5]:
b=[2,9,10]

In [6]:
c=a+b

In [7]:
c

[1, 2, 3, 4, 5, 7, 2, 9, 10]

In [8]:
t=(1,2,3,4,5)

In [9]:
t1=(1,2,3)


In [10]:
print(t[0])

1


In [11]:
set={1,1,3,3,7,7}
set

{1, 3, 7}

In [12]:
set.add(0)
set

{0, 1, 3, 7}

In [13]:
set.update({4,4,5,5,6,6})
set

{0, 1, 3, 4, 5, 6, 7}

In [14]:
set.remove(1)
set

{0, 3, 4, 5, 6, 7}

In [15]:
set.clear()
set

set()

In [16]:
a={1,2,3}
b={4,5,6}
d=a|b
d

{1, 2, 3, 4, 5, 6}

In [17]:
print(d)

{1, 2, 3, 4, 5, 6}


In [18]:
c=a&b
print(c)

set()


In [19]:
c=a&b
print(c)


set()


In [20]:
a

{1, 2, 3}

In [21]:
b

{4, 5, 6}

In [22]:
c=a&b
print(c)

set()


In [23]:
a={1,2,3}
b={1,3,4}

In [24]:
c=a&b
print(c)

{1, 3}


In [25]:
money=4000
if money ==3000:
    print("Go ride on KTX")
elif money >=5000:
    print("Go ride on a bus")
else:
    print("Go on your foot")


Go on your foot


In [26]:
sum=0
for i in range(11):
    sum=sum+i
print(sum)


55


In [27]:
list=["wise", "In", "company"]
for s in list:
    print(s)
    

wise
In
company


In [28]:
i=0
while i<10:
    print(i)
    i=i+1


0
1
2
3
4
5
6
7
8
9


In [29]:
food=["apple", "banana", "bread"]
i=0
while i < len(food)
print(food[i])
i=i+1


SyntaxError: invalid syntax (<ipython-input-29-5946fc895295>, line 3)

In [30]:
food=["apple", "banana", "bread"]
i=0
while i < len(food)
print(food[i])
i=i+1

SyntaxError: invalid syntax (<ipython-input-30-5946fc895295>, line 3)

In [31]:
# while문 리스트 출력
food=["apple", "banana", "bread"]
i=0
while i < len(food):
    print(food[i])
    i=i+1

apple
banana
bread


In [32]:
import numpy as np
v1= np.array([1,2,3,4])
print(v1)


[1 2 3 4]


In [33]:
v1=np.arrage(5)
print(v1)


AttributeError: module 'numpy' has no attribute 'arrage'

In [36]:
v1=np.arange(5)
print(v1)

[0 1 2 3 4]


In [37]:
v2=np.arange(1,10,2, dtype=int)
v3=np.aragne(3.5,10.5,2, dtype=float)
print(v2)
print(v3)


AttributeError: module 'numpy' has no attribute 'aragne'

In [38]:
v2=np.arange(1,10,2, dtype=int)
v3=np.arange(3.5,10.5,2, dtype=float)
print(v2)
print(v3)

[1 3 5 7 9]
[3.5 5.5 7.5 9.5]


In [39]:
v4=np.arange(1,10,2)**2
print(v4)
v5=np.aragne(1,10,2)**3
print(v5)


[ 1  9 25 49 81]


AttributeError: module 'numpy' has no attribute 'aragne'

In [40]:
v4=np.arange(1,10,2)**2
print(v4)
v5=np.arange(1,10,2)**3
print(v5)



[ 1  9 25 49 81]
[  1  27 125 343 729]


In [41]:
np.reshape?

In [42]:
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,6)
print(v2)
v3=v1.reshape(2,6, order='F')
print(v3)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [43]:
v1=np.arange(1,5)
print(v1)


[1 2 3 4]


In [44]:
np.arange?

In [45]:
v1.reshape(2,2)


array([[1, 2],
       [3, 4]])

In [46]:
print(np.add(v1,v1))
print(np.subtact(v1,v1))
print(np,multiply(v1,v1))
print(np.dot(v1,v1))


[2 4 6 8]


AttributeError: module 'numpy' has no attribute 'subtact'

In [47]:
print(np.add(v1,v1))
print(np.subtract(v1,v1))
print(np,multiply(v1,v1))
print(np.dot(v1,v1))

[2 4 6 8]
[0 0 0 0]


NameError: name 'multiply' is not defined

In [48]:
print(np.add(v1,v1))
print(np.subtract(v1,v1))
print(np.multiply(v1,v1))
print(np.dot(v1,v1))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
30


In [49]:
print(np.dot(v1,v1))

30


In [50]:
np.dot?

In [51]:
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,3,2, order='F')
print(v2)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
