In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
data=pd.read_csv('breast-cancer-wisconsin.csv')
data.info()
data.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


code  Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0  1000025                5          1           1                  1   
1  1002945                5          4           4                  5   
2  1015425                3          1           1                  1   
3  1016277                6          8           8                  1   
4  1017023                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  Class  
0        1      0  
1        1      0  
2        1      0  
3        1      0  
4        1      0

In [2]:
X=data[data.columns[1:10]]
y=data[['Class']]


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, startify=y, random_state=42)

TypeError: train_test_split() got an unexpected keyword argument 'startify'

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, stratify=y, random_state=42)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)


In [6]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, 
                        random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(S_scaled_train)
model.socre(X_scaled_train, y_train)


NameError: name 'S_scaled_train' is not defined

In [7]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, 
                        random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(x_scaled_train)
model.socre(X_scaled_train, y_train)

NameError: name 'x_scaled_train' is not defined

In [8]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, 
                        random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.socre(X_scaled_train, y_train

SyntaxError: unexpected EOF while parsing (<ipython-input-8-93c38a9c5e02>, line 7)

In [9]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, 
                        random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.socre(X_scaled_train, y_train)

AttributeError: 'BaggingClassifier' object has no attribute 'socre'

In [10]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
model= BaggingClassifier(base_estimator=SVC(), n_estimators=10, 
                        random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.982421875

In [11]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
print("훈련데이터 오차행렬:\n", confusion_train)


훈련데이터 오차행렬:
 [[329   4]
 [  5 174]]


In [12]:
from sklearn.metrics import classification_report
cfroprt_train=classification_report(y_train, pred_train)
print("분류에측 레포트:\n", cfrepot_train)


NameError: name 'cfrepot_train' is not defined

In [13]:
from sklearn.metrics import classification_report
cfreoprt_train=classification_report(y_train, pred_train)
print("분류에측 레포트:\n", cfrepot_train)

NameError: name 'cfrepot_train' is not defined

In [14]:
from sklearn.metrics import classification_report
cfreport_train=classification_report(y_train, pred_train)
print("분류에측 레포트:\n", cfreport_train)

분류에측 레포트:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       333
           1       0.98      0.97      0.97       179

    accuracy                           0.98       512
   macro avg       0.98      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512



In [15]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)


0.9590643274853801

In [16]:
confusion_test=confusion_matrix(y_test, pred_test)
print("테스트데이터 오차행렬:/n", confusion_test)

테스트데이터 오차행렬:/n [[106   5]
 [  2  58]]


In [17]:
from sklearn.metrics import classification_report
cfreport_test=classification_report(pred_test, y_test)
print("분류예측 레포트:\n", cfreport_test)

분류예측 레포트:
               precision    recall  f1-score   support

           0       0.95      0.98      0.97       108
           1       0.97      0.92      0.94        63

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171



In [18]:
data2=pd.read_csv('house_price.csv', encoding='utf-8')
data2.info()
data2.head()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


housing_age  income  bedrooms  households     rooms  house_value
0           23  6.7770  0.141112    2.442244  8.103960       500000
1           49  6.0199  0.160984    2.726688  5.752412       500000
2           35  5.1155  0.249061    1.902676  3.888078       500000
3           32  4.7109  0.231383    1.913669  4.508393       500000
4           21  4.5625  0.255583    3.092664  4.667954       500000

In [19]:
X=data2[data2.columns[1:4]]
y=data2[['house_value']]


In [20]:
from sklearn.model_seletion import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()

scaler.fit(X_train)

X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)


ModuleNotFoundError: No module named 'sklearn.model_seletion'

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()

scaler.fit(X_train)

X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [22]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

model= BaggingRegressor(base_estimator= KNeighborRegressor(), 
                        n_estimatros=10, random_state=0)

model. fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
mdoel.score(X_scaled_train, y_train)


NameError: name 'KNeighborRegressor' is not defined

In [23]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

model= BaggingRegressor(base_estimator= KNeighborsRegressor(), 
                        n_estimatros=10, random_state=0)

model. fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
mdoel.score(X_scaled_train, y_train)



TypeError: __init__() got an unexpected keyword argument 'n_estimatros'

In [24]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

model= BaggingRegressor(base_estimator= KNeighborsRegressor(), 
                        n_estimators=10, random_state=0)

model. fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
mdoel.score(X_scaled_train, y_train)



NameError: name 'mdoel' is not defined

In [25]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

model= BaggingRegressor(base_estimator= KNeighborsRegressor(), 
                        n_estimators=10, random_state=0)

model. fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.6878367267061276

In [26]:
pred_test=mdoel.predict(X_scaled_test)
mdoel>score(X_scaeld_test, y_test)


NameError: name 'mdoel' is not defined

In [27]:
pred_test=mdoel.predict(X_scaled_test)
model>score(X_scaeld_test, y_test)

NameError: name 'mdoel' is not defined

In [28]:
pred_test=mdoel.predict(X_scaled_test)
model.score(X_scaeld_test, y_test)

NameError: name 'mdoel' is not defined

In [29]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaeld_test, y_test)

NameError: name 'X_scaeld_test' is not defined

In [30]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.543534331851393

In [31]:
import numpy as np
from sklearn.metrics import mean_squred_error

MSE_train=mean_squred_error(y_train, pred_train)
MSE_test=mean_squred_error(y_test, pred_test)

print("훈련데이터 RMSE:", np.sqrt(MSE_train))
print("테스트데이터 RMSE:", np.sqrt(MSE_test))



ImportError: cannot import name 'mean_squred_error' from 'sklearn.metrics' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [32]:
import numpy as np
from sklearn.metrics import mean_squared_error 
MSE_train = mean_squared_error(y_train, pred_train)
MSE_test = mean_squared_error(y_test, pred_test)
print("훈련   데이터 RMSE:", np.sqrt(MSE_train))
print("테스트 데이터 RMSE:", np.sqrt(MSE_test))

훈련   데이터 RMSE: 53326.36082582775
테스트 데이터 RMSE: 64590.18572004634


In [33]:
#Ensemble Boosting

In [34]:
import warnings
warnings.filterwarnings('ignore')
data1=pd.read_csv('breast-cancer-wisconsin')
data1(info)
data1(head)


FileNotFoundError: [Errno 2] No such file or directory: 'breast-cancer-wisconsin'

In [35]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
data1=pd.read_csv('breast-cancer-wisconsin.csv', encoding='utf-8')

In [36]:
import warnings
warnings.filterwarnings('ignore')
data1=pd.read_csv('breast-cancer-wisconsin.csv', encoding='utf-8')
data1(info)
data1(head)



NameError: name 'info' is not defined

In [37]:
import warnings
warnings.filterwarnings('ignore')
data1=pd.read_csv('breast-cancer-wisconsin.csv', encoding='utf-8')
data1.info()
data1.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


code  Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0  1000025                5          1           1                  1   
1  1002945                5          4           4                  5   
2  1015425                3          1           1                  1   
3  1016277                6          8           8                  1   
4  1017023                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  Class  
0        1      0  
1        1      0  
2        1      0  
3        1      0  
4        1      0

In [38]:
X=data1[data1.columns[1:10]]
y=data1[['Class']]


In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, stratify=y, random_state=42)



In [40]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxscaler()

scaler.fit(X_train)

X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)



NameError: name 'MinMaxscaler' is not defined

In [41]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

scaler.fit(X_train)

X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [42]:
from sklearn.ensemble import AdaBoostClassifier

model= AdaBoosClassifier(n_estimators=100, random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)



NameError: name 'AdaBoosClassifier' is not defined

In [43]:
from sklearn.ensemble import AdaBoostClassifier

model= AdaBoostClassifier(n_estimators=100, random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

1.0

In [44]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(pred_train, y_train)
print("훈련데이터 오차행렬:\n")

훈련데이터 오차행렬:



In [45]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(pred_train, y_train)
print("훈련데이터 오차행렬:\n", confusion_train)

훈련데이터 오차행렬:
 [[333   0]
 [  0 179]]


In [46]:
from sklearn.metrics import classification_report
cfreport_train=classification_report(y_train, pred_train)
print("분류예측 레포트:\n", cfeport_train)

NameError: name 'cfeport_train' is not defined

In [47]:
from sklearn.metrics import classification_report
cfreport_train=classification_report(y_train, pred_train)
print("분류예측 레포트:\n", cfreport_train)

분류예측 레포트:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [48]:
pred_tst=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)


0.9532163742690059

In [49]:
confusion_test=confusion_matrix(y_test, pred_tst)
print("테스트데이터 오차행렬:\n", confusion_test)

테스트데이터 오차행렬:
 [[106   5]
 [  3  57]]


In [50]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.9532163742690059

In [51]:
confusion_test=confusion_matrix(y_test, pred_test)
print("테스트데이터 오차행렬:\n", confusion_test)

테스트데이터 오차행렬:
 [[106   5]
 [  3  57]]


In [52]:
from sklearn.ensemble import GradientBoostingClassifier
model= GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
                                 max_depth=1, random_state=0)
model.fit(X_scaled_train, y_train)
pred_model=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)



1.0

In [53]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
print("훈련데이터 오차행렬: \n", confusion_train)

훈련데이터 오차행렬: 
 [[333   0]
 [  0 179]]


In [54]:
pred_test=model.predict(X_scaled_test)
model.socre(pred_test, y_test)

AttributeError: 'GradientBoostingClassifier' object has no attribute 'socre'

In [55]:
pred_test=model.predict(X_scaled_test)
model.score(pred_test, y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1.
 0. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [56]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.9649122807017544

In [57]:
confusion_test=confusion_matrix(y_test, pred_test)
print("테스트데이터 오차행렬:\n", confusion_test)

테스트데이터 오차행렬:
 [[106   5]
 [  1  59]]


In [58]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)


0.9649122807017544

In [59]:
data2=pd.read_csv('house_price')
data2.info()
data2.head()


FileNotFoundError: [Errno 2] No such file or directory: 'house_price'

In [60]:
data2=pd.read_csv('house_price,csv', encoding='utf-8')
data2.info()
data2.head()

FileNotFoundError: [Errno 2] No such file or directory: 'house_price,csv'

In [61]:
data2=pd.read_csv('house_price.csv', encoding='utf-8')
data2.info()
data2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17689 entries, 0 to 17688
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   housing_age  17689 non-null  int64  
 1   income       17689 non-null  float64
 2   bedrooms     17689 non-null  float64
 3   households   17689 non-null  float64
 4   rooms        17689 non-null  float64
 5   house_value  17689 non-null  int64  
dtypes: float64(4), int64(2)
memory usage: 829.3 KB


housing_age  income  bedrooms  households     rooms  house_value
0           23  6.7770  0.141112    2.442244  8.103960       500000
1           49  6.0199  0.160984    2.726688  5.752412       500000
2           35  5.1155  0.249061    1.902676  3.888078       500000
3           32  4.7109  0.231383    1.913669  4.508393       500000
4           21  4.5625  0.255583    3.092664  4.667954       500000

In [62]:
X=data2[data2.columns[1:5]]
y=data2[data2['house_value']]


KeyError: "None of [Int64Index([500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000,\n            500000, 500000,\n            ...\n             32500,  30000,  30000,  27500,  26900,  26600,  22500,  17500,\n             14999,  14999],\n           dtype='int64', length=17689)] are in the [columns]"

In [63]:
X=data2[data2.columns[1:5]]
y=data2[['house_value']]

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, random_state=42)

from sklearn.preprocssing import MinMaxScaler

scaler=MinMaxScaler()

scaler.fit(X_train)

X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)



ModuleNotFoundError: No module named 'sklearn.preprocssing'

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, random_state=42)

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

scaler.fit(X_train)

X_scaled_train=scaler.transform(X_train)

In [66]:
from sklearn.ensemble import AdaBoostRegressor
model= AdaBoostRegressor(random_state=0, n_estimators=100)

model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)


0.4353130085971758

In [67]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_train)


ValueError: X has 9 features, but DecisionTreeRegressor is expecting 4 features as input.

In [68]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)


ValueError: X has 9 features, but DecisionTreeRegressor is expecting 4 features as input.

In [69]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

ValueError: X has 9 features, but DecisionTreeRegressor is expecting 4 features as input.

In [70]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [71]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.43568387094087124

In [72]:
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train=mean_squared_error(pred_train, y_train)
MSE_test=mean_squared_error(pred_test, y_test)

print("훈련데이터 RMSE:", np.sqrt(MSE_train))
print("테스트데이터 RMSE:", np.sqrt(MSE_test))



훈련데이터 RMSE: 71722.42012035428
테스트데이터 RMSE: 71816.41231019037


In [73]:
from sklearn.ensemble import GradientBoostingRegressor
model=GradientBoostingRegressor(random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.socre(X_scaled_train, y_train)



AttributeError: 'GradientBoostingRegressor' object has no attribute 'socre'

In [74]:
from sklearn.ensemble import GradientBoostingRegressor
model=GradientBoostingRegressor(random_state=0)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)



0.6178724780500952

In [75]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.5974112241813845

In [76]:
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train= mean_squared_error(y_train, pred_train)
MSE_test= mean_squared_error(y_teest, pred_test)

print("훈련데이터 RMSE:", np.sqrt(MSE_train))
print("테스트데이터 RMSE:", np.sqrt(MSE_test))



NameError: name 'y_teest' is not defined

In [77]:
import numpy as np
from sklearn.metrics import mean_squared_error

MSE_train= mean_squared_error(y_train, pred_train)
MSE_test= mean_squared_error(y_test, pred_test)

print("훈련데이터 RMSE:", np.sqrt(MSE_train))
print("테스트데이터 RMSE:", np.sqrt(MSE_test))

훈련데이터 RMSE: 59000.433545962376
테스트데이터 RMSE: 60658.72886338227


In [78]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
data1=pd.read_csv('breast-cancer-wisconsin.csv', encoding='utf-8')
X=data1[data1.columns[1:10]]
y=data1[["Class"]]

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, stratify=y, random_state=42)

In [80]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [81]:
data1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [82]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

estimatros=[('rf', RandomForestClassifier(n_estimators=10, random_state=42)), 
           ('scr', SVC(random_state=42))]

model= StakcingClassifier(estimators=estimators, final_estimator=LogisticRegression())
model.fit(X_scaled_train, y_train)

pred_train=model.predict(X_scaled_train)
model.score(X_scaled, y_train)



NameError: name 'StakcingClassifier' is not defined

In [83]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

estimators = [('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
              ('svr', SVC(random_state=42))]
model = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.986328125

In [84]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

estimatros=[('rf', RandomForestClassifier(n_estimators=10, random_state=42)), 
           ('svr', SVC(random_state=42))]

model= StakcingClassifier(estimators=estimators, final_estimator=LogisticRegression())
model.fit(X_scaled_train, y_train)

pred_train=model.predict(X_scaled_train)
model.score(X_scaled, y_train)

NameError: name 'StakcingClassifier' is not defined

In [85]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

estimatros=[('rf', RandomForestClassifier(n_estimators=10, random_state=42)), 
           ('svr', SVC(random_state=42))]

model= StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
model.fit(X_scaled_train, y_train)

pred_train=model.predict(X_scaled_train)
model.score(X_scaled, y_train)

NameError: name 'X_scaled' is not defined

In [86]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

estimatros=[('rf', RandomForestClassifier(n_estimators=10, random_state=42)), 
           ('svr', SVC(random_state=42))]

model= StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
model.fit(X_scaled_train, y_train)

pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.986328125

In [87]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
print("훈련데이터 오차행렬 :\n", confusion_train)



훈련데이터 오차행렬 :
 [[330   3]
 [  4 175]]


In [88]:
from sklearn.metrics import classification_report 
cfreport_train=classification_report(y_train, pred_train)
print("분류예측 리포트: \n", cfreport_train)



분류예측 리포트: 
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       333
           1       0.98      0.98      0.98       179

    accuracy                           0.99       512
   macro avg       0.99      0.98      0.98       512
weighted avg       0.99      0.99      0.99       512



In [89]:
pred_test= model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)


0.9649122807017544

In [90]:
confusion_test=confusion_matrix(pred_test, y_test)
print("테스트데이터 오차행렬: \n", confusion_test)



테스트데이터 오차행렬: 
 [[106   1]
 [  5  59]]


In [1]:
from sklearn.metrics import classification_report
cfreport_test=classfication_report(y_test, pred_test)
print("분류예측 보고서: \n", cfreport_test)


NameError: name 'classfication_report' is not defined

In [2]:
from sklearn.metrics import classification_report
cfreport_test=classification_report(y_test, pred_test)
print("분류예측 보고서: \n", cfreport_test)

NameError: name 'y_test' is not defined

In [3]:
from sklearn.metrics import classification_report
cfreport_test=classification_report(y_test, pred_test)
print("분류예측 레포트:\n", cfreport_test)

NameError: name 'y_test' is not defined

In [4]:
data2=pd.read_csv('house_price.csv', encoding='utf-8')
X=data2[data2.columns[1:5]]
y=data2[["house_value"]]

NameError: name 'pd' is not defined

In [5]:
data2=pd.read_csv('house_price.csv', encoding='utf-8')
X=data2[data2.columns[1:5]]
y=data2[["house_value"]]

NameError: name 'pd' is not defined

In [6]:
import pandas ad pd
data2=pd.read_csv('house_price.csv', encoding='utf-8')
X=data2[data2.columns[1:5]]
y=data2[["house_value"]]

SyntaxError: invalid syntax (<ipython-input-6-38854e3ab15f>, line 1)

In [7]:
import pandas as pd
data2=pd.read_csv('house_price.csv', encoding='utf-8')
X=data2[data2.columns[1:5]]
y=data2[["house_value"]]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=42)

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [10]:
import warnings
warnings.filterwarnings('ignore')


In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor

estimators=[('lr', LinearRegression()), ('knn', KNeighborsRegressor())]
model= StackingRegressor(estimators=estimator,
                        finalestimator=RandomForestRegression(n_estimators=10,
                                                              random_state=42))
final_estimator=RandomForestRegression(n_estimators=10,
                                      random_state=42)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_traiin)



NameError: name 'estimator' is not defined

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor

estimators=[('lr', LinearRegression()), ('knn', KNeighborsRegressor())]
model= StackingRegressor(estimators=estimators,
                        finalestimator=RandomForestRegression(n_estimators=10,
                                                              random_state=42))
final_estimator=RandomForestRegression(n_estimators=10,
                                      random_state=42)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_traiin)

NameError: name 'RandomForestRegression' is not defined

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor

estimators=[('lr', LinearRegression()), ('knn', KNeighborsRegressor())]
model= StackingRegressor(estimators=estimators,
                        finalestimator=RandomForestRegressor(n_estimators=10,
                                                              random_state=42))
final_estimator=RandomForestRegression(n_estimators=10,
                                      random_state=42)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_traiin)

TypeError: __init__() got an unexpected keyword argument 'finalestimator'

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor

estimators=[('lr', LinearRegression()), ('knn', KNeighborsRegressor())]
model= StackingRegressor(estimators=estimators,
                        final_estimator=RandomForestRegressor(n_estimators=10,
                                                              random_state=42))
final_estimator=RandomForestRegression(n_estimators=10,
                                      random_state=42)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_traiin)

NameError: name 'RandomForestRegression' is not defined

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor

estimators=[('lr', LinearRegression()), ('knn', KNeighborsRegressor())]
model= StackingRegressor(estimators=estimators,
                        final_estimator=RandomForestRegressor(n_estimators=10,
                                                              random_state=42))
final_estimator=RandomForestRegressor(n_estimators=10,
                                      random_state=42)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_traiin)

NameError: name 'y_traiin' is not defined

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import StackingRegressor

estimators=[('lr', LinearRegression()), ('knn', KNeighborsRegressor())]
model= StackingRegressor(estimators=estimators,
                        final_estimator=RandomForestRegressor(n_estimators=10,
                                                              random_state=42))
final_estimator=RandomForestRegressor(n_estimators=10,
                                      random_state=42)
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.543404932348004

In [17]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)


0.4781188528801523

In [18]:
import numpy as np
from sklearn.metrics import mean_squared_error
MSE_train= mean_squared_error(y_train, pred_train)
MSE_test= mean_squared_error(y_test, pred_test)

print("훈련 데이터 RMSE:", np.sqrt(MSE_train))
print("테스트 데이터 RMSE:", np.sqrt(MSE_test))



훈련 데이터 RMSE: 64493.60476580374
테스트 데이터 RMSE: 69063.45138802647
