In [1]:
import warnings 
warnings.filterwarnings('ignore')
import pandas as pd
data=pd.read_csv("breast-cancer-wisconsin.csv") 
data.info()
data.head()


FileNotFoundError: [Errno 2] No such file or directory: 'breast-cancer-wisconsin'

In [2]:
import warnings 
warnings.filterwarnings('ignore')
import pandas as pd
data=pd.read_csv("breast-cancer-wisconsin.csv") 
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   code                         683 non-null    int64
 1   Clump_Thickness              683 non-null    int64
 2   Cell_Size                    683 non-null    int64
 3   Cell_Shape                   683 non-null    int64
 4   Marginal_Adhesion            683 non-null    int64
 5   Single_Epithelial_Cell_Size  683 non-null    int64
 6   Bare_Nuclei                  683 non-null    int64
 7   Bland_Chromatin              683 non-null    int64
 8   Normal_Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


code  Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0  1000025                5          1           1                  1   
1  1002945                5          4           4                  5   
2  1015425                3          1           1                  1   
3  1016277                6          8           8                  1   
4  1017023                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  Class  
0        1      0  
1        1      0  
2        1      0  
3        1      0  
4        1      0

In [3]:
X=data[data.columns(1:15)]
y=data[['Class']]


SyntaxError: invalid syntax (<ipython-input-3-5339830f81c0>, line 1)

In [4]:
X=data[data.columns(1:10)]
y=data[['Class']]

SyntaxError: invalid syntax (<ipython-input-4-e90c448e4fa7>, line 1)

In [5]:
X=data[data.columns[1:10]]
y=data[['Class']]

In [6]:
import sklearn.model_selection train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, stratify=y, randome_state=42)

SyntaxError: invalid syntax (<ipython-input-6-946281f28e6e>, line 1)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, stratify=y, randome_state=42)

TypeError: train_test_split() got an unexpected keyword argument 'randome_state'

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, stratify=y, random_state=42)

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaeld_test=scaler.transform(X_test)

In [10]:
from sklearn.tree import DecisionTreeclassifier
model=DecisionTreeClassifier()
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)


ImportError: cannot import name 'DecisionTreeclassifier' from 'sklearn.tree' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/__init__.py)

In [11]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

1.0

In [12]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
print("훈련데이터 오차행렬:\n", confusion_train)

훈련데이터 오차행렬:
 [[333   0]
 [  0 179]]


In [13]:
from sklearn.metrics import classification_report
cfreport_train=classification_report(y_train, pred_train)
print("분류예측 레포트:\n", cfreport_train)


분류예측 레포트:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       179

    accuracy                           1.00       512
   macro avg       1.00      1.00      1.00       512
weighted avg       1.00      1.00      1.00       512



In [14]:
pred_test=model.predict(X_scaled_test)
model.socre(X_scaled-test, y_test)

NameError: name 'X_scaled_test' is not defined

In [15]:
pred_test=model.predict(X_scaled_test)
model.socre(X_scaled_test, y_test)

NameError: name 'X_scaled_test' is not defined

In [16]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

NameError: name 'X_scaled_test' is not defined

In [17]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

NameError: name 'X_scaled_test' is not defined

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [19]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.9590643274853801

In [20]:
confusion_test=confusion_matrix(y_test, pred_test)
print("테스트데이터 오차행렬:\n", confusion_test)

테스트데이터 오차행렬:
 [[105   6]
 [  1  59]]


In [21]:
from sklearn.metrics import classification_report
cfreport_test=classification_report(y_test, pred_test)
print("분류예측 레포트:\n", cfreport_test)


분류예측 레포트:
               precision    recall  f1-score   support

           0       0.99      0.95      0.97       111
           1       0.91      0.98      0.94        60

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [22]:
#Max_depth min_samle_leaf

In [23]:
param_grid={'max_depth':range(2,20,2), 'min_samples_leaf': range(1,50,2)}
from sklearn.mdoel_selection import GridSearchCV
grid_search=GridSearchCV(decisionTreeClassifier(), param_grid, cv=5)
grid_search.fit(X_scaled_train, y_train)


ModuleNotFoundError: No module named 'sklearn.mdoel_selection'

In [24]:
param_grid={'max_depth': range(2,20,2), 'min_samples_leaf': range(1,50,2)}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5)
grid_search.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(2, 20, 2),
                         'min_samples_leaf': range(1, 50, 2)})

In [25]:
print("Best Parameter: {}".format(grid_search.best_params_))
print("Best Score: {:.4f}}".format(grid_search.best_score_))
print("TestSet Score: {:.4f}".format(grid_search.score(X_scaled_test, y_test)))

Best Parameter: {'max_depth': 8, 'min_samples_leaf': 1}


ValueError: Single '}' encountered in format string

In [26]:
print("Best Parameter: {}".format(grid_search.best_params_))
print("Best Score: {:.4f}".format(grid_search.best_score_))
print("TestSet Score: {:.4f}".format(grid_search.score(X_scaled_test, y_test)))

Best Parameter: {'max_depth': 8, 'min_samples_leaf': 1}
Best Score: 0.9647
TestSet Score: 0.9649


In [27]:
print("Best Parameter: {}".format(grid_search.best_params_))
print("Best Score: {:.4f}}".format(grid_search.best_score_))
print("TestSet Score: {:.4f}".format(grid_search.score(X_scaled_test, y_test)))

Best Parameter: {'max_depth': 8, 'min_samples_leaf': 1}


ValueError: Single '}' encountered in format string

In [28]:
print("Best Parameter: {}".format(grid_search.best_params_))
print("Best Score: {:.4f}".format(grid_search.best_score_))
print("TestSet Score: {:.4f}".format(grid_search.score(X_scaled_test, y_test)))

Best Parameter: {'max_depth': 8, 'min_samples_leaf': 1}
Best Score: 0.9647
TestSet Score: 0.9649


In [29]:
from scipy.stats import randint
param_distribs={'max_depth': randint(low=1, high=20),
               'min_sampels_leaf': randint(low=1, high=50)}
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(DecisionTreeClassifier, param_distributions=param_distribs, n_iter=20, cv=5)
random_search.fit(X_scaled_train, y_train)

TypeError: Cannot clone object. You should provide an instance of scikit-learn estimator instead of a class.

In [30]:
from scipy.stats import randint
param_distribs = {'max_depth': randint(low=1, high=20), 
                  'min_samples_leaf': randint(low=1, high=50)}
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(DecisionTreeClassifier(), 
                                 param_distributions=param_distribs, n_iter=20, cv=5)
random_search.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_iter=20,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdf4aa1e880>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdf4aa77160>})

In [31]:
from scipy.stats import randint
param_distribs={'max_depth': randint(low=1, high=20),
               'min_sampels_leaf': randint(low=1, high=50)}
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(DecisionTreeClassifier(), param_distributions=param_distribs, n_iter=20, cv=5)
random_search.fit(X_scaled_train, y_train)

ValueError: Invalid parameter min_sampels_leaf for estimator DecisionTreeClassifier(max_depth=7). Check the list of available parameters with `estimator.get_params().keys()`.

In [32]:
from scipy.stats import randint
param_distribs = {'max_depth': randint(low=1, high=20), 
                  'min_samples_leaf': randint(low=1, high=50)}
from sklearn.model_selection import RandomizedSearchCV
random_search=RandomizedSearchCV(DecisionTreeClassifier(), 
                                 param_distributions=param_distribs, n_iter=20, cv=5)
random_search.fit(X_scaled_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_iter=20,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdf4aa1ec40>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdf5839fbb0>})

In [33]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)


1.0

In [34]:
pred_test=model.predict(X_scaledz_test)
model.score(X_scaled_test, y_test)


NameError: name 'X_scaledz_test' is not defined

In [35]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.768918918918919

In [36]:
import numpy as np
from sklearn.mterics import mean_squred_error
MSE_train= mean_squared_eror(y_train, pred_train)
MSE_test=mean_squared_error(y_test, pred_test)
print("훈련 데이터 RMSE:", np.sqrt(MSE_train))
print("테스트 데이터 RMSE:", np.sqrt(MSE_test))


ModuleNotFoundError: No module named 'sklearn.mterics'

In [37]:
import numpy as np
from sklearn.metrics import mean_squred_error
MSE_train= mean_squared_eror(y_train, pred_train)
MSE_test=mean_squared_error(y_test, pred_test)
print("훈련 데이터 RMSE:", np.sqrt(MSE_train))
print("테스트 데이터 RMSE:", np.sqrt(MSE_test))

ImportError: cannot import name 'mean_squred_error' from 'sklearn.metrics' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [38]:
data2=pd.read_csv('house_price.csv', encoding='utf-8')
X=data2[data2.columns[1:5]]
y=data2[["house_value"]]

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=42)

In [40]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_scaled_train=scaler.transform(X_train)
X_scaled_test=scaler.transform(X_test)

In [41]:
import numpy as np
from sklearn.metrics import mean_squred_error
MSE_train= mean_squared_eror(y_train, pred_train)
MSE_test=mean_squared_error(y_test, pred_test)
print("훈련 데이터 RMSE:", np.sqrt(MSE_train))
print("테스트 데이터 RMSE:", np.sqrt(MSE_test))

ImportError: cannot import name 'mean_squred_error' from 'sklearn.metrics' (/Users/Eddie/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

In [42]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_scaled_train, y_train)
pred_train=model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

1.0

In [43]:
from sklearn.metrics import confusion_matrix
confusion_train=confusion_matrix(y_train, pred_train)
print("훈련데이터 오차행렬:\n", confusion_train)

훈련데이터 오차행렬:
 [[ 1  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0 12]]


In [44]:
param_grid={'max_depth': range(2,20,2), 'min_samples_leaf': range(1,50,2)}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5)
grid_search.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(2, 20, 2),
                         'min_samples_leaf': range(1, 50, 2)})

In [45]:
print("Best Parameter: {}".format(grid_search.best_params_))
print("Best Score: {:.4f}".format(grid_search.best_score_))
print("TestSet Score: {:.4f"}.format(grid_search.score(X_scaled_test, y_test)))



SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (<ipython-input-45-94ed72cabc92>, line 3)